'use strict';
/* =====================================================================================================
   QA Center, Pre-Billing QA, Notice of Admission, look-only billing screens, AloraMail, Reports and Tools
   ===================================================================================================== */
function isMedicare(a) { const pay = byId(DB.lists.payers, (a.ins[0] || {}).payer); return !!pay && /MEDICARE/i.test(pay.name); }

/* ---------------------------------------------------------------- QA Center */
const QA_TYPES = ['SN Note', 'OASIS Assessment', '485 Plan of Care', 'Order (General Form)', 'Aide Plan of Care', 'Aide Note'];
function qaItems() {
  const out = []; const A = pid => admOf(pid);
  DB.snNotes.forEach(n => { const v = noteVisit(n); out.push({ key: 'SN Note:' + n.id, type: 'SN Note', id: n.id, pid: n.pid, qa: n.status === 'Completed' ? (n.qa || 'Pending') : 'In Use', visitDate: v ? v.start.slice(0, 10) : n.date, ref: n, date: v ? v.start.slice(0, 10) : n.date }); });
  DB.assessments.forEach(a => out.push({ key: 'OASIS Assessment:' + a.id, type: 'OASIS Assessment', id: a.id, pid: a.pid, qa: a.qa, asmtDate: a.compDate, ref: a, date: a.compDate }));
  DB.f485.forEach(r => out.push({ key: '485 Plan of Care:' + r.id, type: '485 Plan of Care', id: r.id, pid: r.pid, qa: r.qa || (['Completed', 'Signed'].indexOf(r.status) >= 0 ? 'Pending' : 'In Use'), certFrom: r.from, certTo: r.to, ref: r, date: r.from }));
  DB.orders.forEach(o => out.push({ key: 'Order (General Form):' + o.id, type: 'Order (General Form)', id: o.id, pid: o.pid, qa: o.qa || (o.signed && o.received ? 'Pending' : 'In Use'), orderDate: o.date, ref: o, date: o.date }));
  DB.aideDocs.forEach(x => out.push({ key: (x.kind === 'poc' ? 'Aide Plan of Care:' : 'Aide Note:') + x.id, type: x.kind === 'poc' ? 'Aide Plan of Care' : 'Aide Note', id: x.id, pid: x.pid, qa: x.qa || (x.status === 'Completed' ? 'Pending' : 'In Use'), from: x.from, through: x.to, ref: x, date: x.from }));
  return out.filter(i => P(i.pid));
}
ROUTES.qa = {
  render(c) {
    if (!c.init) { c.init = 1; c.type = ''; c.status = 'Completed'; c.from = fmtD(addDays(todayIso(), -30)); c.to = fmtD(todayIso()); c.all = false; c.shown = false; c.sel = ''; }
    S2SRC.qaTypes = { label: v => v, list: q => QA_TYPES.filter(x => x.toLowerCase().includes(q.toLowerCase())).map(x => ({ v: x, label: x })) };
    const f = parseD(c.from) || '0000', t = parseD(c.to) || '9999';
    const rows = () => (c.shown ? qaItems().filter(i => i.type === c.type && i.qa === c.status && (c.all || (i.date >= f && i.date <= t))) : []);
    const tbl = DT(c, 'qa', () => ({ filterBtn: true, sort: 'date', dir: -1, empty: c.shown ? 'No data available in table' : 'No data available in table',
      cols: [{ key: 'sel', label: '', sortable: false, render: r => `<input type="radio" name="qasel" data-act="qaSel" data-key="${esc(r.key)}"${c.sel === r.key ? ' checked' : ''}>` }, { key: 'visit', label: 'Visit Date', text: r => r.visitDate || '', render: r => fmtD(r.visitDate) }, { key: 'asmt', label: 'Asmt Comp Date', blue: true, text: r => r.asmtDate || '', render: r => fmtD(r.asmtDate) }, { key: 'cf', label: 'Cert From', text: r => r.certFrom || '', render: r => fmtD(r.certFrom) }, { key: 'ct', label: 'Cert To', text: r => r.certTo || '', render: r => fmtD(r.certTo) },
        { key: 'od', label: 'Order Date', text: r => r.orderDate || '', render: r => fmtD(r.orderDate) }, { key: 'from', label: 'From', text: r => r.from || '', render: r => fmtD(r.from) }, { key: 'thr', label: 'Through', text: r => r.through || '', render: r => fmtD(r.through) }, { key: 'pt', label: 'Patient', text: r => ptName(P(r.pid)), render: r => esc(ptName(P(r.pid))) }, { key: 'pan', label: 'PAN #', text: r => (admOf(r.pid) || {}).pan || '', render: r => esc((admOf(r.pid) || {}).pan || '') }, { key: 'adm', label: 'Admit Date', text: r => (admOf(r.pid) || {}).admit || '', render: r => fmtD((admOf(r.pid) || {}).admit) }, { key: 'qa', label: 'QA Status', render: r => tagFor(r.qa) }],
      rows: rows(), searchText: r => ptName(P(r.pid)) + ' ' + r.type }));
    return pageHead('Quality Assurance Center', 'Document Type Selection') + (c.shown ? '' : notice('Please select a Document Type and click the "List Documents" button.', '', 1)) +
      `<div class="flex" style="align-items:flex-end;gap:12px;flex-wrap:wrap"><div style="width:240px">${fg('Document type', s2(c, 'type', 'qaTypes', { ph: 'Enter Document...' }))}</div><div style="width:210px">${fg('Status', sel(c, 'status', ['Completed', 'Pending', 'In Use', 'Returned'], { blank: false }))}</div><div style="width:150px">${fg('From', dp(c, 'from'))}</div><div style="width:150px">${fg('Through', dp(c, 'to'))}</div><label class="chk" style="margin-bottom:12px"><input type="checkbox" ${battr(c, 'all')}${c.all ? ' checked' : ''}> All</label></div><button class="btn btn-ok" data-act="qaList">List Documents</button><p class="small">Documents waiting for the DON show under Status Pending. Completed means the DON approved it.</p>
      ${c.shown ? `<div class="flex mt"><button class="btn btn-add" data-act="qaView">${ic('eye')} View</button><button class="btn btn-ok" data-act="qaApprove">Approve (DON)</button><button class="btn btn-del" data-act="qaReturn">Return for correction (DON)</button></div>` : ''}<hr class="hr">${tbl}`;
  },
};
ACT.qaList = el => { const c = ctxOf(el); if (!c.type) { toast('Choose a Document type first.', 'err'); return; } c.shown = true; c.sel = ''; track('qa:listed'); if (c.status === 'Pending') track('qa:listed-pending'); refresh(); };
ACT.qaSel = el => { ctxOf(el).sel = el.dataset.key; };
function qaPicked(c) { if (!c.sel) { toast('Select a document row first.', 'err'); return null; } return qaItems().find(i => i.key === c.sel) || null; }
ACT.qaView = el => { const c = ctxOf(el); const i = qaPicked(c); if (!i) return; track('qa:view'); if (i.type === 'SN Note') go('snnote', { nid: i.id, mode: 'view' }); else if (i.type === 'OASIS Assessment') go('assess-edit', { id: i.id }); else if (i.type === 'Order (General Form)') ACT.ordView({ dataset: { id: i.id } }); else if (i.type === '485 Plan of Care') ACT.f485View({ dataset: { id: i.id } }); else alertBox(i.type, '<p>Aide documents open from Clinical, Aide Documents.</p>'); };
ACT.qaApprove = el => { const c = ctxOf(el); const i = qaPicked(c); if (!i) return; needApproval({ roles: ['DON'], what: 'Approve a document in QA', rule: 'Do not approve or change a clinical document in QA. That is the DON\'s role.', who: 'DON', ref: 'AD1', go: () => { if (i.qa !== 'Pending') { toast('Only Pending documents can be approved. This one is ' + i.qa + '.', 'err'); return; } i.ref.qa = 'Completed'; i.ref.qaBy = DB.session.userId; save(); track('qa:approved'); simLog('info', 'QA approved: ' + i.type); c.sel = ''; refresh(); toast('Approved. QA Status is now Completed.', 'ok'); } }); };
ACT.qaReturn = el => { const c = ctxOf(el); const i = qaPicked(c); if (!i) return; needApproval({ roles: ['DON'], what: 'Return a document in QA', rule: 'Do not approve or change a clinical document in QA. That is the DON\'s role.', who: 'DON', ref: 'AD1', go: () => { const m = ctxNew({ why: '' }); modal({ title: 'Return for correction', ctx: m, size: 'sm', body: mc => fg('Reason (the clinician sees this)', txt(mc, 'why', { rows: 3 }), { req: 1 }), buttons: [{ label: 'Return', cls: 'btn-ok', click: () => { if (!m.why.trim()) { toast('Write the reason.', 'err'); return false; } i.ref.qa = 'Returned'; i.ref.qaReason = m.why.trim(); if (i.type === 'SN Note') { i.ref.status = 'In Use'; i.ref.nurseSigned = false; if (i.ref.sig) delete i.ref.sig.nurse; } save(); track('qa:returned'); simLog('info', 'QA returned: ' + i.type); c.sel = ''; refresh(); toast('Returned to the clinician.', 'ok'); } }, { label: 'Cancel', cls: 'btn-del' }] }); } }); };

/* ---------------------------------------------------------------- Pre-Billing QA */
function preBillChecks(a) {
  const p = P(a.pid), ins = a.ins[0], med = isMedicare(a); const c = [];
  c.push(['Payer and insurance dates entered', !!ins && !!ins.payer && !!ins.from]);
  if (med) c.push(['Medicare ID on the patient and on the insurance', !!p.medicare && !!(ins && ins.memberId)]);
  c.push(['Physician on the admission', !!a.physId]);
  if (med) { c.push(['SOC OASIS completed and approved in QA', DB.assessments.some(x => x.pid === p.id && asmtIsSoc(x) && x.qa === 'Completed')]); c.push(['485 signed and received', DB.f485.some(x => x.pid === p.id && x.recd)]); c.push(['Face-to-Face document on file', DB.docs.some(d => d.pid === p.id && !d.deleted && /f2f|face/i.test(d.title))]); c.push(['Notice of Admission (NOA) submitted', ((DB.noa.find(n => n.aid === a.id)) || {}).status === 'Submitted']); }
  c.push(['Orders signed and received', DB.orders.filter(o => o.pid === p.id).every(o => o.signed && o.received)]);
  c.push(['Every past billable visit is Completed', DB.visits.filter(v => v.pid === p.id && v.billable && v.start < nowIso() && v.status !== 'A').every(v => v.status === 'C')]);
  c.push(['SN notes signed and QA Completed', DB.snNotes.filter(n => n.pid === p.id).every(n => n.status === 'Completed' && n.qa === 'Completed')]);
  c.push(['No unresolved EVV conflicts', !evvConflicts().some(x => x.v.pid === p.id)]);
  return c;
}
function preBillItems() { return DB.admissions.filter(a => !a.draft && !a.inactive && P(a.pid)).map(a => ({ a, checks: preBillChecks(a) })).filter(x => x.checks.some(k => !k[1])); }
ROUTES.prebill = {
  render(c) {
    if (!c.init) { c.init = 1; c.from = fmtD(addDays(todayIso(), -60)); c.to = fmtD(todayIso()); c.mode = 'due'; c.payer = ''; c.type = 'RAP'; c.shown = false; }
    const f = parseD(c.from) || '0000', t = parseD(c.to) || '9999';
    const rows = () => (c.shown ? DB.admissions.filter(a => !a.draft && P(a.pid) && a.admit <= t && (!a.dischDate || a.dischDate >= f) && (!c.payer || (a.ins[0] || {}).payer === c.payer)).map(a => ({ a, checks: preBillChecks(a) })).filter(x => c.mode === 'both' || x.checks.some(k => !k[1])) : []);
    const tbl = DT(c, 'pb', () => ({ filterBtn: true, sort: 'pt', empty: c.shown ? 'No patients have items due but not done' : 'No data available in table', cols: [{ key: 'pt', label: 'Patient', blue: true, text: r => ptName(P(r.a.pid)), render: r => esc(ptName(P(r.a.pid))) }, { key: 'adm', label: 'Admit Date', text: r => r.a.admit, render: r => fmtD(r.a.admit) }, { key: 'payer', label: 'Payer', text: r => payerName((r.a.ins[0] || {}).payer), render: r => esc(payerName((r.a.ins[0] || {}).payer)) }, { key: 'n', label: 'Missing', text: r => String(r.checks.filter(k => !k[1]).length), sort: r => r.checks.filter(k => !k[1]).length, render: r => `<b style="color:${r.checks.some(k => !k[1]) ? '#c0392b' : '#3c763d'}">${r.checks.filter(k => !k[1]).length}</b>` }, { key: 'items', label: 'Checks', sortable: false, render: r => r.checks.map(k => `<div style="color:${k[1] ? '#3c763d' : '#c0392b'}">${k[1] ? '&#10003;' : '&#10007;'} ${esc(k[0])}</div>`).join('') }], rows: rows(), searchText: r => ptName(P(r.a.pid)) }));
    return pageHead('Pre-Billing QA', '') + `<div class="box"><div class="flex" style="gap:40px;align-items:flex-start;flex-wrap:wrap"><div><div class="sec sm" style="background:none;color:#333;border-bottom:1px solid #ccc;padding-left:0">Statement Period</div><div class="flex">${fg('From', dp(c, 'from'))}${fg('Through', dp(c, 'to'))}</div><div class="sec sm" style="background:none;color:#333;border-bottom:1px solid #ccc;padding-left:0">Payer</div><div style="width:300px">${s2(c, 'payer', 'payers', { ph: 'Enter Payer', clear: 1 })}</div></div>
      <div><div class="box">${radio(c, 'mode', 'due', 'Due but not done')}<br>${radio(c, 'mode', 'both', 'Both done and not done')}</div><div class="box">${radio(c, 'type', 'RAP', 'RAP')}<br>${radio(c, 'type', 'EOE', 'End of Episode (EOE)')}</div></div></div><div class="flex" style="justify-content:flex-end"><button class="btn btn-ok" data-act="pbShow">Show List</button></div>${tbl}</div><p class="small">Ready means every item is verified. Do not guess missing information. Ask the Administrator or DON. Do not generate or send claims.</p>`;
  },
};
ACT.pbShow = el => { const c = ctxOf(el); c.shown = true; track('prebill:shown'); refresh(); };

/* ---------------------------------------------------------------- Notice of Admission (Generate Claims PDGM) */
function noaList() {
  return DB.admissions.filter(a => !a.draft && isMedicare(a) && P(a.pid)).map(a => { const rec = DB.noa.find(n => n.aid === a.id) || null; return { id: a.id, aid: a.id, pid: a.pid, soc: a.admit, due: addDays(a.admit, 5), status: rec ? rec.status : 'Not started', rec, medicare: P(a.pid).medicare }; });
}
ROUTES.noa = {
  render(c) {
    const tbl = DT(c, 'noa', () => ({ sort: 'due', cols: [{ key: 'act', label: 'Action', sortable: false, blue: true, render: r => `<button class="btn btn-add btn-sm" data-act="noaPrep" data-aid="${r.aid}">${r.status === 'Not started' ? 'Prepare NOA' : 'Open'}</button> <button class="btn btn-ok btn-sm" data-act="noaSubmit" data-aid="${r.aid}">Submit</button>` }, { key: 'pt', label: 'Patient', text: r => ptName(P(r.pid)), render: r => esc(ptName(P(r.pid))) }, { key: 'soc', label: 'SOC Date', text: r => r.soc, render: r => fmtD(r.soc) }, { key: 'mid', label: 'Medicare ID', render: r => (r.medicare ? esc(r.medicare) : '<b style="color:#c0392b">MISSING</b>') }, { key: 'due', label: 'Zenith target (5 calendar days)', text: r => r.due, render: r => fmtD(r.due) },
      { key: 'left', label: 'Days left', text: r => String(diffDays(r.due, todayIso())), sort: r => diffDays(r.due, todayIso()), render: r => { if (r.status === 'Submitted') return ''; const d = diffDays(r.due, todayIso()); return `<b style="color:${d < 0 ? '#c0392b' : d <= 1 ? '#d68910' : '#333'}">${d < 0 ? 'LATE by ' + (-d) + ' days' : d + ' days'}</b>`; } }, { key: 'status', label: 'Status', render: r => `<span class="tag ${r.status === 'Submitted' ? 'g' : r.status === 'Prepared' ? 'b' : 'o'}">${esc(r.status)}</span>` }, { key: 'conf', label: 'Practice confirmation', render: r => esc((r.rec && r.rec.conf) || '') }], rows: noaList() }));
    return pageHead('Generate Claims PDGM', 'Notice of Admission') + `${simplified()}<div class="note warn"><span>The real Alora billing screen here acts on real claims. In the simulator you can <b>prepare and submit a practice NOA</b>. Nothing is ever sent to Medicare. <b>Generate Claims</b> is blocked.</span></div><div class="flex"><button class="btn btn-gray" data-act="blockBill" data-w="Generate Claims PDGM">Generate Claims</button></div>${tbl}<p class="small">Zenith target: submit the NOA within 5 calendar days of the SOC date. The Administrator confirms the current CMS rule. Do not submit an NOA without the Administrator.</p>`;
  },
};
ACT.noaPrep = el => {
  const a = byId(DB.admissions, el.dataset.aid); const p = P(a.pid); const issues = []; if (!p.medicare) issues.push('Medicare ID is missing.'); if (!a.admit) issues.push('SOC date is unclear.');
  const m = ctxNew({ ok1: false, ok2: false });
  modal({ title: 'Prepare Notice of Admission (practice)', ctx: m, size: 'lg', body: c => `${issues.length ? notice('STOP and ask the Administrator: ' + issues.join(' '), 'err') : ''}<div class="kv"><div>Patient</div><div>${esc(ptName(p))}</div><div>Medicare ID</div><div>${esc(p.medicare || 'MISSING')}</div><div>SOC date</div><div>${fmtD(a.admit)}</div><div>Physician</div><div>${esc(physName(a.physId))}</div><div>Zenith target date</div><div>${fmtD(addDays(a.admit, 5))}</div></div><hr class="hr">${chk(c, 'ok1', 'I checked the SOC date and Medicare ID against the record')}<br>${chk(c, 'ok2', 'The Administrator reviewed this NOA')}`, buttons: [{ label: 'Save as Prepared', cls: 'btn-ok', click: () => { if (issues.length) { toast('Fix the missing items first. Do not guess.', 'err'); return false; } if (!m.ok1) { toast('Check the SOC date and Medicare ID first.', 'err'); return false; } let rec = DB.noa.find(n => n.aid === a.id); if (!rec) { rec = { id: uid('NOA'), aid: a.id, pid: a.pid, status: 'Prepared', preparedAt: nowIso(), reviewed: !!m.ok2, conf: '' }; DB.noa.push(rec); } else if (rec.status !== 'Submitted') { rec.status = 'Prepared'; rec.reviewed = !!m.ok2; } save(); track('noa:prepared'); simLog('info', 'NOA prepared for ' + ptName(p)); refresh(); } }, { label: 'Close', cls: 'btn-close' }] });
};
ACT.noaSubmit = el => {
  const a = byId(DB.admissions, el.dataset.aid); const p = P(a.pid); const rec = DB.noa.find(n => n.aid === a.id);
  if (!rec) { toast('Prepare the NOA first.', 'err'); return; } if (rec.status === 'Submitted') { toast('Already submitted (practice).', 'ok'); return; }
  needApproval({ roles: ['Administrator'], what: 'Submit a Notice of Admission', rule: 'Do not submit an NOA without the Administrator. Late NOAs reduce payment.', who: 'Administrator', ref: 'BI2', go: () => confirmBox('Submit the practice NOA?', '<p>This is a <b>practice</b> submission. Nothing is sent to Medicare. A made-up confirmation number is recorded.</p>', () => { rec.status = 'Submitted'; rec.submittedAt = nowIso(); rec.conf = 'PRACTICE-' + (7000 + DB.noa.length); rec.late = todayIso() > addDays(a.admit, 5); save(); track('noa:submitted'); if (rec.late) track('noa:late'); simLog('info', 'Practice NOA submitted for ' + ptName(p) + (rec.late ? ' (LATE)' : '')); refresh(); toast('Practice NOA submitted. Nothing was sent.', 'sim'); }, { yes: 'Submit (practice)', no: 'Cancel' }) });
};

/* ---------------------------------------------------------------- look-only billing screens */
function lookOnly(title, sub, what, conseq, btn) {
  return { render(c) { return pageHead(title, sub) + `${simplified()}<div class="note warn"><span><b>Look only.</b> The real screen acts on real claims and real money. In the simulator the button below is blocked and explained. Nothing is created, sent or posted.</span></div><div class="box"><h4>${esc(title)}</h4><div class="row c2">${fg('Statement period from', dp(c, 'f'))}${fg('Through', dp(c, 't'))}${fg('Payer', s2(c, 'p', 'payers', { ph: 'Enter Payer' }))}${fg('Patient', s2(c, 'pt', 'patientsAll', { ph: 'Enter Patient' }))}</div><div class="flex" style="justify-content:flex-end"><button class="btn btn-gray" data-act="blockBill" data-w="${esc(what)}" data-c="${esc(conseq)}">${esc(btn)}</button></div></div><p class="small">Zenith rule: never click ${esc(btn)} while training. Ask the Administrator before you open billing screens.</p>`; } };
}
ROUTES.genclaims = lookOnly('Generate Claims', 'Summary', 'Generate Claims', 'In the real Alora this creates real claims for the selected patients.', 'Generate Claims');
ROUTES.eclaim = lookOnly('Electronic Claim File', 'Summary', 'Electronic Claim File', 'In the real Alora this builds the file that is sent to a payer.', 'Create Electronic Claim File');
ROUTES.invoice = lookOnly('Non-insurance Invoice', 'Summary', 'Generate Invoices', 'In the real Alora this creates real invoices for private pay patients.', 'Generate Invoices');
ROUTES.batchprint = lookOnly('Batch Printing of Claims', 'Summary', 'Batch Print Claims', 'In the real Alora this prints real claims.', 'Print Claims');
ROUTES.postpay = lookOnly('Post Payment', 'Summary', 'Post Payment', 'In the real Alora this records real money received against a claim.', 'Post Payment');
ACT.blockBill = el => { track('billing:blocked'); neverDo(el.dataset.w, el.dataset.c || 'In the real Alora this acts on real claims or money.', 'Zenith rule: never click Generate Claims, Generate Claims PDGM, Electronic Claim File, Generate Invoices, or Post Payment while training.'); };
ROUTES.claimsum = { render(c) { const rows = DB.admissions.filter(a => !a.draft && P(a.pid)); const tbl = DT(c, 'cs', () => ({ sort: 'pt', cols: [{ key: 'pt', label: 'Patient', text: r => ptName(P(r.pid)), render: r => esc(ptName(P(r.pid))) }, { key: 'pan', label: 'PAN #', render: r => esc(r.pan) }, { key: 'payer', label: 'Payer', text: r => payerName((r.ins[0] || {}).payer), render: r => esc(payerName((r.ins[0] || {}).payer)) }, { key: 'adm', label: 'Admit Date', text: r => r.admit, render: r => fmtD(r.admit) }, { key: 'cl', label: 'Claims', render: () => '0 (simulator creates none)' }], rows })); return pageHead('Claim Summary', 'Summary') + `${simplified()}<p class="note sim">Look only. The simulator never creates claims.</p>${tbl}`; } };
ROUTES.artrans = { render(c) { const tbl = DT(c, 'ar', () => ({ cols: [{ key: 'd', label: 'Date' }, { key: 'p', label: 'Patient' }, { key: 'k', label: 'Type' }, { key: 'a', label: 'Amount' }], rows: [], empty: 'No transactions (the simulator never posts payments)' })); return pageHead('Transaction Log', 'Summary') + `${simplified()}<p class="note sim">Look only. No payments exist in the simulator.</p>${tbl}`; } };

/* ---------------------------------------------------------------- AloraMail */
ROUTES.mail = {
  render(c, p) {
    if (p.compose && !c._comp) { c._comp = true; setTimeout(() => composeMail({}), 0); }
    c.box = c.box || 'in'; const me = DB.session.userId;
    const list = DB.messages.filter(m => (c.box === 'in' ? m.to === me : m.from === me)).sort((a, b) => (a.date < b.date ? 1 : -1));
    const tbl = DT(c, 'ml', () => ({ sort: 'date', dir: -1, cols: [{ key: 'act', label: '', sortable: false, render: r => rowIcons([{ ic: 'eye', t: 'Open', act: 'mailOpen', data: { id: r.id }, cls: 'view' }]) }, { key: 'who', label: c.box === 'in' ? 'From' : 'To', text: r => (byId(DB.users, c.box === 'in' ? r.from : r.to) || {}).name || '', render: r => `<span style="${r.read || c.box !== 'in' ? '' : 'font-weight:700'}">${esc((byId(DB.users, c.box === 'in' ? r.from : r.to) || {}).name || '')}</span>` }, { key: 'subject', label: 'Subject', render: r => `<a data-act="mailOpen" data-id="${r.id}" style="${r.read || c.box !== 'in' ? '' : 'font-weight:700'}">${esc(r.subject)}</a>` }, { key: 'date', label: 'Date', text: r => r.date, render: r => fmtDT(r.date) }], rows: list }));
    return pageHead('AloraMail', c.box === 'in' ? 'Inbox' : 'Sent') + `<div class="bar"><h2>${ic('mail')} AloraMail</h2><button class="btn btn-add" data-act="mailNew">${ic('plus')} New message</button></div><div class="btngrp" style="margin:6px 0"><button class="${c.box === 'in' ? 'on' : ''}" data-act="mailBox" data-b="in">Inbox</button><button class="${c.box === 'out' ? 'on' : ''}" data-act="mailBox" data-b="out">Sent</button></div><p class="small">AloraMail stays inside Alora. In the simulator it only reaches the other practice logins (use Practice as at the top to read it). Never put a SSN, Medicare number or date of birth in a message.</p>${tbl}`;
  },
};
ACT.mailBox = el => { const c = ctxOf(el); c.box = el.dataset.b; c.dt = {}; refresh(); };
ACT.mailNew = () => composeMail({});
ACT.mailOpen = el => { const m = byId(DB.messages, el.dataset.id); if (m.to === DB.session.userId && !m.read) { m.read = true; save(); buildNav(); navActive(PAGE.route); } track('mail:opened'); modal({ title: esc(m.subject), size: 'lg', body: `<div class="kv"><div>From</div><div>${esc((byId(DB.users, m.from) || {}).name || '')}</div><div>To</div><div>${esc((byId(DB.users, m.to) || {}).name || '')}</div><div>Date</div><div>${fmtDT(m.date)}</div></div><hr class="hr"><div style="white-space:pre-wrap">${esc(m.body)}</div>${m.attach ? `<p class="small mt">${ic('clip')} Attachment: ${esc(m.attach)}</p>` : ''}`, buttons: [{ label: 'Reply', cls: 'btn-add', click: () => { composeMail({ to: m.from, subject: 'Re: ' + m.subject }); } }, { label: 'Close', cls: 'btn-close' }] }); refresh(); };
function composeMail(o) {
  o = o || {}; const m = ctxNew({ to: o.to || '', subject: o.subject || '', body: o.body || '' });
  modal({ title: 'New message', ctx: m, size: 'lg', body: c => `${fg('To', s2(c, 'to', 'users', { ph: 'Choose a person' }), { req: 1 })}${fg('Subject', inp(c, 'subject'), { req: 1 })}${fg('Message', txt(c, 'body', { rows: 6 }))}<p class="small">Practice only. The message is delivered to another practice login inside this browser. Nothing is emailed.</p>`,
    buttons: [{ label: 'Send', cls: 'btn-ok', click: () => {
      if (!m.to || !m.subject.trim()) { toast('Choose who to send it to and write a subject.', 'err'); return false; }
      const send = () => { DB.messages.push({ id: uid('M'), to: m.to, from: DB.session.userId, subject: m.subject.trim(), body: m.body, date: nowIso(), read: false, attach: o.body && /attached/i.test(o.body) ? o.subject : '' }); save(); track('mail:sent'); simLog('info', 'AloraMail sent to ' + (byId(DB.users, m.to) || {}).name); toast('Sent (practice).', 'ok'); if (PAGE.route === 'mail') refresh(); else buildNav(); };
      if (/\b\d{3}-?\d{2}-?\d{4}\b|ssn|\b[0-9][A-Z][A-Z0-9]\d-?[A-Z][A-Z0-9]\d-?[A-Z][A-Z0-9]\d{2}\b|medicare number/i.test(m.body + ' ' + m.subject)) { modal({ title: 'Private information', kind: 'warn', size: 'sm', body: '<p>This message looks like it contains a SSN, a Medicare number or similar private data.</p><p class="mt">Zenith rule: never type a SSN, DOB, Medicare number or pay into a message. Remove it.</p>', buttons: [{ label: 'Go back and remove it (recommended)', cls: 'btn-ok', click: () => simLog('good', 'Removed private data from a message') }, { label: 'Send anyway (practice)', cls: 'btn-or', click: () => { simLog('override', 'Sent a message with private data (practice)'); send(); m._modal.close(); } }] }); return false; }
      send(); } }, { label: 'Cancel', cls: 'btn-del' }] });
}

/* ---------------------------------------------------------------- Reports (simplified) */
const REPORTS = [
  ['Active Census', () => { const rows = DB.admissions.filter(a => a.status === 'Admitted' && !a.draft); return [['Patient', 'PAN', 'Admit date', 'Payer', 'Physician'], rows.map(a => [ptName(P(a.pid)), a.pan, fmtD(a.admit), payerName((a.ins[0] || {}).payer), physName(a.physId)])]; }],
  ['Visits for the Last 7 Days', () => { const f = addDays(todayIso(), -7); return [['Date', 'Time', 'Patient', 'Caregiver', 'Status'], DB.visits.filter(v => v.start.slice(0, 10) >= f && v.start.slice(0, 10) <= todayIso()).sort((a, b) => (a.start < b.start ? -1 : 1)).map(v => [fmtD(v.start), fmtT(v.start) + ' - ' + fmtT(v.end), ptName(P(v.pid)), stName(ST(v.cgId)), visitStatus(v).label])]; }],
  ['Credentials Expiring in 30 Days', () => { const out = []; DB.staff.forEach(s => CRED_ITEMS.forEach(([k, l]) => { const c = s.creds[k]; if (c && c.exp && diffDays(c.exp, todayIso()) <= 30) out.push([stName(s), l, fmtD(c.exp), diffDays(c.exp, todayIso()) < 0 ? 'EXPIRED' : 'Due soon']); })); return [['Staff', 'Item', 'Expires', 'Status'], out]; }],
  ['Orders Not Signed or Not Received', () => [['Patient', 'Order', 'Order date', 'Sent', 'Received', 'Signed'], DB.orders.filter(o => !o.signed || !o.received).map(o => [ptName(P(o.pid)), o.title, fmtD(o.date), fmtD(o.sent), fmtD(o.received), o.signed ? 'Yes' : 'No'])]],
  ['Notes Still in DRAFT', () => [['Patient', 'Visit date', 'Nurse'], DB.snNotes.filter(n => n.status !== 'Completed').map(n => [ptName(P(n.pid)), fmtD(n.date), stName(ST(n.cgId))])]],
  ['Missed and Cancelled Visits', () => [['Date', 'Patient', 'Caregiver', 'Status', 'Reason'], DB.visits.filter(v => v.status === 'M' || v.status === 'A').map(v => [fmtD(v.start), ptName(P(v.pid)), stName(ST(v.cgId)), vcode(v.status), v.missedReason || ''])]],
  ['EVV Conflicts', () => [['Date', 'Patient', 'Caregiver', 'Reason'], evvConflicts().map(x => [fmtD(x.v.start), ptName(P(x.v.pid)), stName(ST(x.v.cgId)), x.reason])]],
];
ROUTES.reports = {
  render(c) { return pageHead('Reports', 'Summary') + `${simplified()}<p class="small">The real Alora has many more reports. These run on the practice data.</p><div class="cardgrid">${REPORTS.map((r, i) => `<div class="card" style="cursor:pointer" data-act="repRun" data-i="${i}"><h4>${esc(r[0])}</h4><div class="small">Click to run</div></div>`).join('')}</div>`; },
};
ACT.repRun = el => { const r = REPORTS[+el.dataset.i]; const [head, rows] = r[1](); track('report:run'); printPreview(r[0], `<h2>${esc(r[0])} (practice)</h2><p class="small">Run ${fmtDT(nowIso())}</p><table class="t"><thead><tr>${head.map(h => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(x => `<tr>${x.map(y => `<td>${esc(y)}</td>`).join('')}</tr>`).join('') || `<tr><td colspan="${head.length}">No rows</td></tr>`}</tbody></table>`); };

/* ---------------------------------------------------------------- Tools (Administrator) */
ROUTES.faxconf = { render(c) { return pageHead('Fax Confirmation', 'Summary') + `${simplified()}<p class="note sim">The simulator never sends a fax, so this list is always empty.</p><table class="t"><thead><tr><th>Date</th><th>To</th><th>Document</th><th>Result</th></tr></thead><tbody><tr><td colspan="4" class="none">No faxes (the simulator never sends one)</td></tr></tbody></table>`; } };
ROUTES.undelete = {
  render(c) {
    const rows = DB.deleted.map(d => { if (d.kind === 'patient') { const x = byId(DB.docs, d.id); return x && x.deleted ? { d, x, who: ptName(P(x.pid)), title: x.title } : null; } const s = ST(d.sid); const x = s && s.docs.find(y => y.id === d.id); return x && x.deleted ? { d, x, who: stName(s), title: x.title } : null; }).filter(Boolean);
    return pageHead('Undelete Documents', 'Summary') + `${simplified()}<p class="small">Administrator tool. Use it only with written authorization. A document in the wrong chart: STOP, do not delete, tell the Administrator.</p><table class="t"><thead><tr><th>Action</th><th>Document</th><th>Belongs to</th><th>Kind</th><th>Deleted</th></tr></thead><tbody>${rows.map((r, i) => `<tr><td><button class="btn btn-add btn-sm" data-act="undel" data-i="${i}">Undelete</button></td><td>${esc(r.title)}</td><td>${esc(r.who)}</td><td>${r.d.kind}</td><td>${fmtDT(r.x.deletedAt || '')}</td></tr>`).join('') || '<tr><td colspan="5" class="none">No deleted documents</td></tr>'}</tbody></table>`;
  },
};
ACT.undel = el => { const c = PAGE.ctx; const rows = DB.deleted; const list = rows.map(d => { if (d.kind === 'patient') { const x = byId(DB.docs, d.id); return x && x.deleted ? { d, x } : null; } const s = ST(d.sid); const x = s && s.docs.find(y => y.id === d.id); return x && x.deleted ? { d, x } : null; }).filter(Boolean); const r = list[+el.dataset.i]; if (!r) return; r.x.deleted = false; DB.deleted = DB.deleted.filter(z => z !== r.d); save(); track('tools:undelete'); simLog('info', 'Undeleted a document'); toast('Document restored.', 'ok'); refresh(); };
['oasisexport', 'oasissegue', 'cahps'].forEach(r => { const t = { oasisexport: ['Oasis Export', 'In the real Alora this builds the OASIS file that is sent to the state and CMS.'], oasissegue: ['OASIS Segue', 'In the real Alora this sends assessments to the OASIS submission service.'], cahps: ['CAHPS Export', 'In the real Alora this builds a survey file that is sent to a vendor.'] }[r]; ROUTES[r] = { render(c) { return pageHead(t[0], 'Summary') + `${simplified()}<div class="note warn"><span><b>Blocked in the simulator.</b> ${esc(t[1])} Zenith rule: never export an OASIS for John Doe or anyone during training.</span></div><div class="box"><div class="row c2">${fg('From', dp(c, 'f'))}${fg('Through', dp(c, 't'))}</div><div class="flex" style="justify-content:flex-end"><button class="btn btn-gray" data-act="blockBill" data-w="${esc(t[0])}" data-c="${esc(t[1])}">Export</button></div></div>`; } }; });
