'use strict';
/* =====================================================================================================
   Human Resources and Setup: Staff (Caregiver) list and record, folders, setup lists, user access, COVID screening
   ===================================================================================================== */
const EMP_TYPES = ['Employee', 'Contractor', 'Per Diem'];
const PROFILE_BTNS = ['Print Staff Profile', 'Track Absences', 'Staff (Caregiver) Communication Log', 'Enable CareConnect', 'HHVBP Legacy'];
ROUTES.staff = {
  render(c, p) {
    if (p.add && !c._added) { c._added = true; setTimeout(() => ACT.stAdd(), 0); }
    if (c.inactive === undefined) c.inactive = false;
    const tbl = DT(c, 'st', () => ({ filterBtn: true, sort: 'name',
      cols: [{ key: 'act', label: 'Action', sortable: false, blue: true, render: r => rowIcons([{ ic: 'edit', t: 'Open the record', act: 'stOpen', data: { id: r.id } }, { ic: 'trash', t: 'Delete (never)', act: 'stDelete', data: { id: r.id }, cls: 'del' }]) },
        { key: 'name', label: 'Staff (Caregiver) Name', blue: true, text: r => stName(r), render: r => esc(stName(r)) + (r.active ? '' : ' <span class="tag gr">Inactive</span>') }, { key: 'disc', label: 'Discipline', text: r => r.disc, render: r => esc(r.disc) }],
      rows: DB.staff.filter(s => !s.draft && (c.inactive || s.active)), searchText: r => stName(r) + ' ' + r.empId + ' ' + r.disc }));
    return pageHead('Staff Demographics', 'Find Staff Member') + `<div class="bar"><h2>${ic('user')} Staff (Caregivers)</h2><button class="btn btn-add" data-act="stAdd">${ic('plus')} Add</button></div>${tbl}<label class="chk mt"><input type="checkbox" ${battr(c, 'inactive')} data-rr="1"${c.inactive ? ' checked' : ''}> Include inactive staff</label>`;
  },
};
ACT.stOpen = el => { track('staff:open'); go('staff-rec', { id: el.dataset.id }); };
ACT.stAdd = () => needApproval({ roles: ['Administrator', 'HR'], what: 'Add a new staff member (+ Add)', rule: 'Do not create a new staff record without first searching (H1). A new hire only, never an existing person.', who: 'Administrator or HR', ref: 'H1, H2', go: () => { track('staff:addclick'); go('staff-rec', { id: 'NEW', add: 1 }); } });
ACT.stDelete = el => needApproval({ roles: ['Administrator'], what: 'Click the red trash icon on a staff member', rule: 'NEVER click the red trash icon. Former staff are made inactive, not deleted. Never click Delete unless the Administrator authorized it in writing.', who: 'Administrator, in writing', ref: 'H1, R2', go: () => confirmBox('Delete this staff record?', '<p>The record is removed from the practice data. (Reset restores it.) Real Alora keeps former staff as inactive.</p>', () => { DB.staff = DB.staff.filter(s => s.id !== el.dataset.id); save(); simLog('override', 'Deleted a staff record (practice)'); refresh(); }, { yes: 'Delete', no: 'Cancel' }) });

function blankStaff() { return { id: 'NEW', last: '', first: '', mi: '', empId: '', disc: '', active: true, empType: '', dob: '', sex: '', ssn: '', title: '', hire: '', term: '', addr1: '', addr2: '', city: '', state: 'FL', zip: '', covZips: '', lic: '', exclPayroll: false, phones: { home: '', cell: '', work: '', pager: '' }, noText: false, fax: '', email: '', emName: '', emPhone: '', comments: '', creds: {}, docs: [], absences: [], commLog: [], pay: [], avail: {}, cc: { enabled: false, user: '', invited: '' } }; }
function stToForm(s) { const d = JSON.parse(JSON.stringify(s)); d.dobT = fmtD(s.dob); d.hireT = fmtD(s.hire); d.termT = fmtD(s.term); d.credT = {}; CRED_ITEMS.forEach(([k]) => { const c = s.creds[k] || {}; d.credT[k] = { exp: fmtD(c.exp), remark: c.remark || '' }; }); return d; }
ROUTES['staff-rec'] = {
  render(c, p) {
    const isNew = p.id === 'NEW';
    if (!c.d) { const src = isNew ? blankStaff() : ST(p.id); if (!src) return notice('Staff member not found.', 'err'); c.d = stToForm(src); c.orig = JSON.stringify(c.d); c.tab = 'demo'; }
    const d = c.d; const tabs = tabsHtml([{ k: 'demo', l: 'Staff Demographics' }, { k: 'cred', l: 'Credential Tracking' }, { k: 'pay', l: 'Staff (Caregiver) Standard Pay Rate' }, { k: 'docs', l: 'Electronic Staff Records' }, { k: 'avail', l: 'Availability' }].map(t => Object.assign(t, { off: isNew && t.k !== 'demo' })), c.tab, 'stTab');
    const titles = { demo: 'Staff Demographics', cred: 'Credential Tracking', pay: 'Standard Pay Rate', docs: 'Electronic Staff Records', avail: 'Availability' };
    let pane = { demo: stDemo, cred: stCred, pay: stPay, docs: stDocs, avail: stAvail }[c.tab](c, d, isNew);
    return pageHead(titles[c.tab], c.tab === 'cred' ? 'Summary' : '') + tabs + `<div class="tabpane">${pane}</div>${c.tab !== 'demo' ? `<div class="flex mt">${[PROFILE_BTNS[0], PROFILE_BTNS[2]].map(b => `<button class="btn btn-add" data-act="${b === PROFILE_BTNS[0] ? 'stProfile' : 'stComm'}">${b}</button>`).join('')}</div>` : ''}`;
  },
};
ACT.stTab = el => { const c = ctxOf(el); if (el.classList.contains('off')) { toast('Alora opens the other tabs after the record is saved.', 'sim'); return; } c.tab = el.dataset.k; track('staff:tab:' + c.tab); refresh(); };
function stDemo(c, d, isNew) {
  const b = c.bad || {};
  return `<div class="sec">Staff (Caregiver) Demographics</div><div class="flex" style="align-items:flex-start;gap:20px"><div style="width:200px;border:1px dotted #aaa;height:200px;display:flex;align-items:center;justify-content:center;color:#666;text-align:center">Profile Photo<br><span class="small">(not used in the simulator)</span></div><div class="grow"><h4 style="font:400 20px var(--font)">Staff Member Name</h4><div class="row" style="grid-template-columns:2fr 2fr 80px">${fg('Last Name', inp(c, 'd.last', { cls: b.last ? 'bad' : '' }), { req: 1 })}${fg('First Name', inp(c, 'd.first', { cls: b.first ? 'bad' : '' }), { req: 1 })}${fg('MI', inp(c, 'd.mi', { max: 1 }))}</div><div class="row" style="grid-template-columns:1fr 1fr 1fr">${fg('Employee ID', inp(c, 'd.empId', { cls: b.empId ? 'bad' : '' }), { req: 1 })}${fg('Discipline', s2(c, 'd.disc', 'disciplines', { ph: 'Enter...' }), { req: 1 })}<div class="fg"><label class="chk" style="margin-top:24px"><input type="checkbox" data-act="stActive" ${battr(c, 'd.active')}${d.active ? ' checked' : ''}> Active</label></div></div>${fg('Employment Type', sel(c, 'd.empType', EMP_TYPES), {})}</div></div>
  <hr class="hr"><div class="row c3">${fg('Date of Birth', dp(c, 'd.dobT'))}${fg('Sex', sel(c, 'd.sex', ['Male', 'Female', 'Unknown']))}${fg('SSN', inp(c, 'd.ssn', { type: 'password' }))}${fg('Title', inp(c, 'd.title'))}${fg('Hire Date', dp(c, 'd.hireT'))}${fg('Termination Date:', dp(c, 'd.termT'))}</div>
  <div class="row" style="grid-template-columns:1fr">${fg('Address Line 1', inp(c, 'd.addr1'))}${fg('Address Line 2', inp(c, 'd.addr2'))}</div><div class="row" style="grid-template-columns:3fr 100px 1fr">${fg('City', inp(c, 'd.city'))}${fg('State', inp(c, 'd.state'))}${fg('Zip', inp(c, 'd.zip'))}</div>
  ${fg('Covered Zip Codes <a data-act="zipHelp">&#9432;</a>', inp(c, 'd.covZips'))}${fg('Professional License Number', inp(c, 'd.lic'))}<div class="fg">${chk(c, 'd.exclPayroll', 'Exclude from payroll')}</div>
  <div class="row c4">${fg('Home Phone', inp(c, 'd.phones.home'))}${fg('Cell Phone', inp(c, 'd.phones.cell'))}${fg('Work Phone', inp(c, 'd.phones.work'))}${fg('Pager', inp(c, 'd.phones.pager'))}</div><div class="fg">${chk(c, 'd.noText', 'Do not send text messages')}</div><div class="row c2">${fg('Fax', inp(c, 'd.fax'))}${fg('E-mail', inp(c, 'd.email', { type: 'email' }))}${fg('Emergency Contact', inp(c, 'd.emName'))}${fg('Emergency Contact Phone Number', inp(c, 'd.emPhone'))}</div>
  <div class="box"><h4>Staff Regions list</h4><table class="t"><thead><tr><th>Region name</th><th>Action</th></tr></thead><tbody><tr><td colspan="2" class="none">No regions (practice)</td></tr></tbody></table></div>${fg('Comments', txt(c, 'd.comments', { rows: 3 }))}
  <hr class="hr"><div class="flex" style="justify-content:flex-end"><button class="btn" style="background:#8bc34a;color:#fff" data-act="stSave">Save &amp; Close</button><button class="btn btn-save" style="background:#3b8fd0" data-act="stCancel">Cancel</button></div>
  <div class="flex mt" style="gap:8px">${PROFILE_BTNS.map(b => `<button class="btn btn-add${isNew && b !== PROFILE_BTNS[0] ? ' dis' : ''}" data-act="${{ 'Print Staff Profile': 'stProfile', 'Track Absences': 'stAbs', 'Staff (Caregiver) Communication Log': 'stComm', 'Enable CareConnect': 'stCC', 'HHVBP Legacy': 'stHhvbp' }[b]}">${b}</button>`).join('')}</div>`;
}
ACT.zipHelp = () => alertBox('Covered Zip Codes', '<p>List the zip codes this caregiver can cover, separated by commas. The Scheduler uses it for "Show Caregivers in Patient\'s Region | Zip Code".</p>');
ACT.stHhvbp = () => alertBox('HHVBP Legacy', '<p class="stub">' + simplified() + ' This button opens a value-based purchasing form in the real Alora. It is not in Zenith\'s manual, so it is not simulated.</p>');
ACT.stActive = el => { const c = ctxOf(el); c.d.active = el.checked; if (!el.checked) { simLog('info', 'Marked a staff member inactive (the right way to remove someone)'); track('staff:inactive'); } };
function stDirty(c) { return JSON.stringify(c.d) !== c.orig; }
ACT.stCancel = el => { const c = ctxOf(el); if (c.params.new || c.params.id === 'NEW') confirmBox('Cancel', '<p>This unsaved document will be deleted. Are you sure?</p>', () => { track('staff:newcancel'); go('staff'); }, { yes: 'Yes', no: 'No' }); else { if (stDirty(c)) { c.d = stToForm(ST(c.params.id)); c.orig = JSON.stringify(c.d); refresh(); toast('What you typed was undone.', 'ok'); } else go('staff'); } };
ACT.stSave = el => {
  const c = ctxOf(el), d = c.d, isNew = c.params.id === 'NEW'; c.bad = {};
  if (!d.last.trim()) c.bad.last = 1; if (!d.first.trim()) c.bad.first = 1; if (!d.empId.trim()) c.bad.empId = 1;
  if (Object.keys(c.bad).length || !d.disc) { c.tab = 'demo'; refresh(); toast('Last name, first name, Employee ID and Discipline are required.', 'err'); return; }
  const dup = DB.staff.find(x => x.id !== c.params.id && ((x.last === d.last.trim().toUpperCase() && x.first === d.first.trim().toUpperCase()) || x.empId === d.empId.trim()));
  const apply = () => {
    const rec = isNew ? Object.assign(blankStaff(), { id: uid('S') }) : ST(c.params.id);
    ['last', 'first', 'mi', 'empId', 'disc', 'active', 'empType', 'sex', 'ssn', 'title', 'addr1', 'addr2', 'city', 'state', 'zip', 'covZips', 'lic', 'exclPayroll', 'noText', 'fax', 'email', 'emName', 'emPhone', 'comments'].forEach(k => (rec[k] = d[k]));
    rec.last = rec.last.trim().toUpperCase(); rec.first = rec.first.trim().toUpperCase(); rec.empId = rec.empId.trim(); rec.dob = parseD(d.dobT) || ''; rec.hire = parseD(d.hireT) || ''; rec.term = parseD(d.termT) || ''; rec.phones = d.phones;
    if (isNew) { rec.avail = {}; ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'].forEach(x => (rec.avail[x] = { on: true, from: '08:00', to: '17:00' })); ['Sat', 'Sun'].forEach(x => (rec.avail[x] = { on: false, from: '', to: '' })); DB.staff.push(rec); }
    save(); track(isNew ? 'staff:created' : 'staff:saved'); simLog('info', (isNew ? 'Created staff ' : 'Saved staff ') + stName(rec)); toast('Saved.', 'ok'); if (isNew) go('staff-rec', { id: rec.id }); else { c.d = stToForm(rec); c.orig = JSON.stringify(c.d); go('staff'); }
  };
  if (isNew && dup) { modal({ title: 'Possible duplicate staff record', kind: 'warn', size: 'sm', body: `<p><b>${esc(stName(dup))}</b> (Employee ID ${esc(dup.empId)}) looks like the same person or the same ID.</p><p class="mt">Zenith rule: STOP. Two records for one person is never allowed. Tell the Administrator.</p>`, buttons: [{ label: 'Stop (recommended)', cls: 'btn-ok', click: () => simLog('good', 'Stopped at a possible duplicate staff record') }, { label: 'Create anyway (practice)', cls: 'btn-or', click: () => { simLog('override', 'Created a duplicate staff record (practice)'); apply(); } }] }); return; }
  apply();
};
ACT.stProfile = el => { const c = ctxOf(el); const s = ST(c.params.id) || c.d; track('staff:profile'); printPreview('Staff Profile', `<h2>Staff Profile (practice)</h2><table class="t"><tbody><tr><td>Name</td><td>${esc(stName(s))}</td></tr><tr><td>Employee ID</td><td>${esc(s.empId)}</td></tr><tr><td>Discipline</td><td>${esc(s.disc)}</td></tr><tr><td>Hire date</td><td>${fmtD(s.hire || parseD(s.hireT))}</td></tr><tr><td>Active</td><td>${s.active ? 'Yes' : 'No'}</td></tr></tbody></table><p class="small">The real profile can include private data. Never email or text it.</p>`); };

/* Credential Tracking */
function stCred(c, d) {
  const tbl = DT(c, 'cr', () => ({ sort: 'code', noPaging: false, firstLast: false, sizes: [10, 25],
    cols: [{ key: 'code', label: 'Code', blue: true, text: r => r[0], render: r => esc(r[0]) }, { key: 'desc', label: 'Item Description', text: r => r[1], render: r => esc(r[1]) }, { key: 'exp', label: 'Expiration Date', sortable: false, text: r => (d.credT[r[0]] || {}).exp || '', render: r => dp(c, 'd.credT.' + r[0] + '.exp') + (credFlag(d.credT[r[0]].exp)) }, { key: 'remark', label: 'Remark', sortable: false, text: r => (d.credT[r[0]] || {}).remark || '', render: r => inp(c, 'd.credT.' + r[0] + '.remark') }],
    rows: CRED_ITEMS }));
  return `${tbl}<p class="small">Do not enter an expiration date you have not seen on the actual document. Expired items are marked in red; items due in 30 days are marked in orange.</p><div class="flex mt" style="justify-content:flex-end"><button class="btn btn-save" data-act="stCredSave">Save</button><button class="btn btn-cancel" data-act="stCredCancel">Cancel</button><button class="btn btn-close" data-act="stClose">Close</button></div>`;
}
function credFlag(txt2) { const iso = parseD(txt2); if (!iso) return ''; const dd = diffDays(iso, todayIso()); if (dd < 0) return ' <span class="tag r">Expired</span>'; if (dd <= 30) return ' <span class="tag o">Due in ' + dd + ' days</span>'; return ''; }
ACT.stClose = () => go('staff');
ACT.stCredCancel = el => { const c = ctxOf(el); c.d.credT = stToForm(ST(c.params.id)).credT; refresh(); };
ACT.stCredSave = el => {
  const c = ctxOf(el); const s = ST(c.params.id); const changed = []; const bad = [];
  CRED_ITEMS.forEach(([k, l]) => { const t = c.d.credT[k]; const iso = parseD(t.exp); if (t.exp && !iso) bad.push(l); const old = s.creds[k] || {}; if ((iso || '') !== (old.exp || '') || (t.remark || '') !== (old.remark || '')) changed.push([k, l, iso, t.remark]); });
  if (bad.length) { toast('Check the date for: ' + bad.join(', ') + ' (MM/DD/YYYY).', 'err'); return; }
  if (!changed.length) { toast('Nothing changed.', 'ok'); return; }
  const m = ctxNew({ seen: false });
  modal({ title: 'Confirm before saving', kind: 'warn', size: 'sm', ctx: m, body: cc => `<p>You are changing ${changed.length} credential${changed.length === 1 ? '' : 's'}:</p><ul>${changed.map(x => `<li>${esc(x[1])}: ${esc(x[2] ? fmtD(x[2]) : '(blank)')}</li>`).join('')}</ul>${chk(cc, 'seen', 'I saw these dates on the actual documents')}`, buttons: [{ label: 'Save', cls: 'btn-ok', click: () => { if (!m.seen) { toast('Zenith rule: do not enter a date you have not seen on the actual document.', 'err'); return false; } changed.forEach(([k, l, iso, rem]) => { s.creds[k] = { exp: iso || '', remark: rem || '' }; }); save(); track('staff:credsaved'); simLog('info', 'Saved credential dates for ' + stName(s)); c.orig = JSON.stringify(c.d); refresh(); toast('Credentials saved.', 'ok'); } }, { label: 'Cancel', cls: 'btn-del' }] });
};

/* Pay rate and availability */
function stPay(c, d) {
  const s = ST(c.params.id);
  return `<div class="flex"><h4 style="font:400 22px var(--font)">Standard Pay Rate</h4><button class="btn btn-add btn-sm" data-act="payAdd">${ic('plus')} Add</button></div><table class="t"><thead><tr><th>Effective From</th><th>Pay Type</th><th>Rate</th></tr></thead><tbody>${s.pay.slice().sort((a, b) => (a.from < b.from ? 1 : -1)).map(r => `<tr><td>${fmtD(r.from)}</td><td>${esc(r.type)}</td><td>$${esc(r.rate)}</td></tr>`).join('') || '<tr><td colspan="3" class="none">No pay rates</td></tr>'}</tbody></table><p class="small">Do not change a pay rate without written approval from the Administrator. Never type pay into email or text.</p>`;
}
ACT.payAdd = el => { const c = ctxOf(el); const s = ST(c.params.id); needApproval({ roles: ['Administrator'], what: 'Add or change a pay rate', rule: 'Do not change a pay rate without written approval from the Administrator.', who: 'Administrator, in writing', ref: 'H5', go: () => { const m = ctxNew({ r: { from: fmtD(todayIso()), type: 'Hourly', rate: '', approved: '' } }); modal({ title: 'Add Standard Pay Rate', ctx: m, size: 'sm', body: mc => fg('Effective From', dp(mc, 'r.from')) + fg('Pay Type', sel(mc, 'r.type', ['Hourly', 'Per Visit', 'Salary'], { blank: false })) + fg('Rate', inp(mc, 'r.rate')) + fg('Written approval from (name and date)', inp(mc, 'r.approved')), buttons: [{ label: 'Save', cls: 'btn-ok', click: () => { if (!parseD(m.r.from) || !(+m.r.rate > 0)) { toast('Enter an effective date and a rate.', 'err'); return false; } if (!m.r.approved.trim()) { toast('Write who approved the change in writing.', 'err'); return false; } s.pay.push({ id: uid('PR'), from: parseD(m.r.from), type: m.r.type, rate: (+m.r.rate).toFixed(2), approved: m.r.approved }); save(); track('staff:payrate'); simLog('info', 'Added a pay rate for ' + stName(s)); refresh(); } }, { label: 'Cancel', cls: 'btn-del' }] }); } }); };
function stAvail(c, d) {
  const s = ST(c.params.id); c.av = c.av || JSON.parse(JSON.stringify(s.avail || {}));
  return `<table class="t"><thead><tr><th>Day</th><th>Available</th><th>From</th><th>To</th></tr></thead><tbody>${['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(dn => { const a = c.av[dn] = c.av[dn] || { on: false, from: '', to: '' }; return `<tr><td>${dn}</td><td>${chk(c, 'av.' + dn + '.on', '', { rr: 1 })}</td><td>${inp(c, 'av.' + dn + '.from', { dis: !a.on, ph: '08:00' })}</td><td>${inp(c, 'av.' + dn + '.to', { dis: !a.on, ph: '17:00' })}</td></tr>`; }).join('')}</tbody></table><p class="small">24 hour time, like 08:00 and 17:00. Change availability only with written approval. The Scheduler sees this when picking a caregiver.</p><div class="flex mt" style="justify-content:flex-end"><button class="btn btn-save" data-act="avSave">Save</button><button class="btn btn-close" data-act="stClose">Close</button></div>`;
}
ACT.avSave = el => { const c = ctxOf(el); const s = ST(c.params.id); const ok = Object.keys(c.av).every(k => !c.av[k].on || (/^\d{1,2}:\d{2}$/.test(c.av[k].from) && /^\d{1,2}:\d{2}$/.test(c.av[k].to))); if (!ok) { toast('Use 24 hour times like 08:00 for each available day.', 'err'); return; } Object.keys(c.av).forEach(k => { ['from', 'to'].forEach(f => { if (c.av[k][f] && c.av[k][f].length === 4) c.av[k][f] = '0' + c.av[k][f]; }); }); s.avail = JSON.parse(JSON.stringify(c.av)); save(); track('staff:avail'); simLog('info', 'Saved availability for ' + stName(s)); toast('Saved.', 'ok'); };

/* Electronic Staff Records */
function stDocs(c, d) {
  const s = ST(c.params.id); if (c.all === undefined) { c.all = true; c.folder = ''; }
  const tbl = DT(c, 'sd', () => ({ sort: 'created', dir: -1,
    cols: [{ key: 'act', label: 'Action', sortable: false, blue: true, render: r => rowIcons([{ ic: 'eye', t: 'Open', act: 'sdView', data: { id: r.id }, cls: 'view' }, { ic: 'edit', t: 'Edit', act: 'sdEdit', data: { id: r.id } }, { ic: 'trash', t: 'Delete', act: 'sdDel', data: { id: r.id }, cls: 'del' }]) }, { key: 'title', label: 'Title', render: r => `<a data-act="sdView" data-id="${r.id}">${esc(r.title)}</a>` }, { key: 'created', label: 'Created Date', blue: true, text: r => r.created, render: r => fmtD(r.created) }, { key: 'folder', label: 'Folder Name', render: r => esc(r.folder) }],
    rows: s.docs.filter(x => !x.deleted && (c.all || !c.folder || x.folder === c.folder)) }));
  return `<div class="bar"><h2>${ic('user')} ${esc(stName(s))} <span class="small">Employee ID ${esc(s.empId)}</span></h2><button class="btn btn-add" data-act="sdAdd">${ic('plus')} Add</button></div><p class="small">Confirm the name and Employee ID before you upload. A staff document never goes into a patient's Electronic Health Records.</p><div class="flex" style="align-items:flex-end"><div style="width:360px">${fg('Folder:', s2(c, 'folder', 'stFolders', { ph: 'Enter Folder name', rr: 1 }))}</div><label class="chk" style="margin-bottom:12px"><input type="checkbox" ${battr(c, 'all')} data-rr="1"${c.all ? ' checked' : ''}> All</label></div>${tbl}`;
}
S2SRC.stFolders.onpick = (c, v, path) => { if (path === 'folder') c.all = !v; };
ACT.sdAdd = el => { const c = ctxOf(el); docUploadModal({ kind: 'staff', sid: c.params.id }); };
ACT.sdView = el => { const c = ctxOf(el); const d = ST(c.params.id).docs.find(x => x.id === el.dataset.id); viewFile(d); };
ACT.sdEdit = el => { const c = ctxOf(el); const d = ST(c.params.id).docs.find(x => x.id === el.dataset.id); const m = ctxNew({ t: d.title, f: d.folder, cm: d.comment || '' }); modal({ title: 'Electronic Staff Record', ctx: m, size: 'lg', body: mc => fg('Record Name', inp(mc, 't')) + fg('Folder', s2(mc, 'f', 'stFolders', { ph: 'Enter Folder name' })) + fg('Comments', txt(mc, 'cm', { rows: 3 })), buttons: [{ label: 'Save & Close', cls: 'btn-ok', click: () => { if (!m.t.trim() || !m.f) { toast('Record Name and Folder are required.', 'err'); return false; } d.title = m.t.trim(); d.folder = m.f; d.comment = m.cm; save(); refresh(); } }, { label: 'Cancel', cls: 'btn-del' }] }); };
ACT.sdDel = el => { const c = ctxOf(el); needApproval({ roles: ['Administrator'], what: 'Delete a staff document', rule: 'Never delete without the Administrator\'s written authorization.', who: 'Administrator, in writing', ref: 'R2', go: () => { const d = ST(c.params.id).docs.find(x => x.id === el.dataset.id); d.deleted = true; DB.deleted.push({ kind: 'staff', id: d.id, sid: c.params.id }); save(); refresh(); } }); };

/* Absences, communication log, CareConnect */
ACT.stAbs = el => {
  const c = ctxOf(el); const s = ST(c.params.id); if (!s || c.params.id === 'NEW') { toast('Save the record first.', 'err'); return; } track('staff:absences');
  const m = ctxNew({ a: { from: '', to: '', reason: '', approved: '' } });
  const mod = modal({ title: 'Track Absences: ' + esc(stName(s)), ctx: m, size: 'lg', body: mc => `<table class="t"><thead><tr><th>From</th><th>Through</th><th>Reason</th><th>Approved by</th><th></th></tr></thead><tbody>${s.absences.map((a, i) => `<tr><td>${fmtD(a.from)}</td><td>${fmtD(a.to)}</td><td>${esc(a.reason)}</td><td>${esc(a.approved || '')}</td><td><button class="ico-btn ico-del" data-act="absDel" data-i="${i}">${ic('trash')}</button></td></tr>`).join('') || '<tr><td colspan="5" class="none">No absences</td></tr>'}</tbody></table><div class="box mt"><h4>Add an absence</h4><div class="row c2">${fg('From', dp(mc, 'a.from'), { req: 1 })}${fg('Through', dp(mc, 'a.to'))}${fg('Reason (time off, call out)', inp(mc, 'a.reason'), { req: 1 })}${fg('Approved by (written request)', inp(mc, 'a.approved'))}</div><button class="btn btn-add btn-sm" data-act="absAdd">${ic('plus')} Add absence</button></div>`, buttons: [{ label: 'Close', cls: 'btn-close' }] });
  m.s = s;
};
ACT.absAdd = el => {
  const m = ctxOf(el); const s = m.s; const f = parseD(m.a.from), t = parseD(m.a.to) || f; if (!f || !m.a.reason.trim()) { toast('Enter the From date and the reason.', 'err'); return; }
  const over = DB.visits.filter(v => v.cgId === s.id && v.status !== 'A' && v.start.slice(0, 10) >= f && v.start.slice(0, 10) <= t);
  const save1 = () => { s.absences.push({ id: uid('AB'), from: f, to: t, reason: m.a.reason.trim(), approved: m.a.approved }); save(); track('staff:absence-added'); simLog('info', 'Absence added for ' + stName(s)); m.a = { from: '', to: '', reason: '', approved: '' }; m._modal.rerender(); };
  if (over.length) { modal({ title: 'This absence overlaps scheduled visits', kind: 'warn', size: 'lg', body: `<p>${esc(stName(s))} has <b>${over.length}</b> visit${over.length === 1 ? '' : 's'} scheduled during this absence. Zenith rule: <b>tell the Scheduler now</b> so the visits are covered.</p><table class="t"><thead><tr><th>Date</th><th>Time</th><th>Patient</th></tr></thead><tbody>${over.map(v => `<tr><td>${fmtD(v.start)}</td><td>${fmtT(v.start)} - ${fmtT(v.end)}</td><td>${esc(ptName(P(v.pid)))}</td></tr>`).join('')}</tbody></table>`, buttons: [{ label: 'Save the absence and tell the Scheduler', cls: 'btn-ok', click: () => { simLog('good', 'Absence saved; Scheduler to be told about ' + over.length + ' visits'); DB.messages.push({ id: uid('M'), to: (DB.users.find(u => u.role === 'Scheduler') || {}).id, from: DB.session.userId, subject: 'Absence overlaps visits: ' + stName(s), body: 'Practice message: ' + stName(s) + ' is absent ' + fmtD(f) + ' to ' + fmtD(t) + ' (' + m.a.reason + '). ' + over.length + ' visit(s) need coverage.', date: nowIso(), read: false }); track('staff:absence-overlap'); save1(); } }, { label: 'Cancel', cls: 'btn-del' }] }); return; }
  save1();
};
ACT.absDel = el => { const m = ctxOf(el); m.s.absences.splice(+el.dataset.i, 1); save(); m._modal.rerender(); };
ACT.stComm = el => {
  const c = ctxOf(el); const s = ST(c.params.id); if (!s || c.params.id === 'NEW') { toast('Save the record first.', 'err'); return; } const m = ctxNew({ note: '', type: 'Conversation' }); track('staff:commlog');
  modal({ title: 'Staff (Caregiver) Communication Log: ' + esc(stName(s)), ctx: m, size: 'lg', body: mc => `<table class="t"><thead><tr><th>Date</th><th>Type</th><th>Note</th><th>Entered by</th></tr></thead><tbody>${s.commLog.slice().reverse().map(x => `<tr><td>${fmtDT(x.date)}</td><td>${esc(x.type)}</td><td>${esc(x.note)}</td><td>${esc((byId(DB.users, x.by) || {}).name || '')}</td></tr>`).join('') || '<tr><td colspan="4" class="none">No entries</td></tr>'}</tbody></table><div class="box mt"><h4>Add an entry</h4>${fg('Type', sel(mc, 'type', ['Conversation', 'Phone call', 'Email', 'Warning', 'Other'], { blank: false }))}${fg('Note (never put SSN or pay here)', txt(mc, 'note', { rows: 3 }))}<button class="btn btn-add btn-sm" data-act="scAdd">${ic('plus')} Add entry</button></div>`, buttons: [{ label: 'Close', cls: 'btn-close' }] });
  m.s = s;
};
ACT.scAdd = el => { const m = ctxOf(el); if (!m.note.trim()) { toast('Write a note.', 'err'); return; } m.s.commLog.push({ id: uid('SC'), date: nowIso(), type: m.type, note: m.note.trim(), by: DB.session.userId }); save(); track('staff:comm-added'); m.note = ''; m._modal.rerender(); };
ACT.stCC = el => {
  const c = ctxOf(el); const s = ST(c.params.id); if (!s || c.params.id === 'NEW') { toast('Save the record first. CareConnect is turned on for a saved record.', 'err'); return; }
  const go2 = () => {
    const problems = []; if (!(s.phones.cell || '').trim()) problems.push('The cell phone number is missing.'); if (!(s.email || '').trim()) problems.push('The e-mail address is missing.'); const cp = credProblems(s); if (cp.length) problems.push('Credentials are not verified: ' + cp.join('; ') + '.'); if (!s.empId) problems.push('Employee ID is missing.');
    const open = () => { const m = ctxNew({ user: s.cc.user || (s.first + '.' + s.last).toLowerCase() }); modal({ title: 'Enable CareConnect', ctx: m, size: 'sm', body: mc => `<p>${esc(stName(s))} (${esc(s.disc)})</p>${fg('CareConnect login (assigned by the Administrator)', inp(mc, 'user'), { req: 1 })}<p class="small">Never give a staff member another person's login. If Alora asks to buy or add licenses, STOP and tell the Administrator.</p>`, buttons: [{ label: 'Enable', cls: 'btn-ok', click: () => { if (!m.user.trim()) { toast('Enter the login.', 'err'); return false; } s.cc = { enabled: true, user: m.user.trim().toLowerCase(), invited: todayIso() }; save(); track('staff:cc-enabled'); simLog('info', 'Enabled CareConnect for ' + stName(s)); toast('CareConnect enabled. They can sign in on the practice phone.', 'ok'); refresh(); } }, { label: 'Cancel', cls: 'btn-del' }] }); };
    if (problems.length) { modal({ title: 'Check before you enable CareConnect', kind: 'warn', size: 'sm', body: `<ul>${problems.map(x => `<li>${esc(x)}</li>`).join('')}</ul><p class="mt">Zenith rule: do not turn on CareConnect before the record and credentials are verified.</p>`, buttons: [{ label: 'Stop (recommended)', cls: 'btn-ok', click: () => simLog('good', 'Stopped before enabling CareConnect: ' + problems[0]) }, { label: 'Enable anyway (practice)', cls: 'btn-or', click: () => { simLog('override', 'Enabled CareConnect with open problems: ' + problems.join(' ')); open(); } }] }); return; }
    open();
  };
  needApproval({ roles: ['Administrator'], what: 'Enable CareConnect for ' + stName(s), rule: 'HR or the Administrator turns on CareConnect for each new field employee, with the Administrator\'s approval.', who: 'Administrator', ref: 'H6', go: go2 });
};

/* ---------------------------------------------------------------- record folders */
function folderPage(title, plural, key, bar) {
  return { render(c) {
    const tbl = DT(c, 'fo', () => ({ sort: 'n', cols: [{ key: 'act', label: 'Action', sortable: false, blue: true, render: r => rowIcons([{ ic: 'edit', t: 'Rename', act: 'foEdit', data: { n: r.n, k: key } }, { ic: 'trash', t: 'Delete', act: 'foDel', data: { n: r.n, k: key }, cls: 'del' }]) }, { key: 'n', label: plural, text: r => r.n, render: r => esc(r.n) }], rows: DB.lists[key].map(n => ({ n })) }));
    return pageHead(title, 'Summary') + `<div class="bar"><h2>${ic('folder')} ${esc(bar)}</h2><button class="btn btn-add" data-act="foAdd" data-k="${key}">${ic('plus')} Add</button></div>${tbl}<p class="small">Folders are set by the Administrator. If the folder you need is not listed, do not guess. Ask the Administrator.</p>`;
  } };
}
ROUTES.ptfolders = folderPage('Patient Record Folders', 'Patient Record Folder', 'ptFolders', 'Patient Record Folders');
ROUTES.stfolders = folderPage('Staff (Caregiver) Record Folders', 'Staff Record Folders', 'staffFolders', 'Staff Record Folders');
ACT.foAdd = el => needApproval({ roles: ['Administrator'], what: 'Add a record folder', rule: 'Only the Administrator adds folders. Do not guess a folder name.', who: 'Administrator', ref: 'AD3', go: () => { const m = ctxNew({ n: '' }); modal({ title: 'Add folder', ctx: m, size: 'sm', body: c => fg('Folder name (capital letters)', inp(c, 'n')), buttons: [{ label: 'Save', cls: 'btn-ok', click: () => { const n = m.n.trim().toUpperCase(); if (!n) { toast('Enter a name.', 'err'); return false; } if (DB.lists[el.dataset.k].indexOf(n) >= 0) { toast('That folder already exists.', 'err'); return false; } DB.lists[el.dataset.k].push(n); save(); track('folder:added'); simLog('info', 'Added folder ' + n); refresh(); } }, { label: 'Cancel', cls: 'btn-del' }] }); } });
ACT.foEdit = el => needApproval({ roles: ['Administrator'], what: 'Rename a folder', rule: 'Only the Administrator changes folders.', who: 'Administrator', ref: 'AD3', go: () => { const m = ctxNew({ n: el.dataset.n }); modal({ title: 'Edit folder', ctx: m, size: 'sm', body: c => fg('Folder name', inp(c, 'n')), buttons: [{ label: 'Save', cls: 'btn-ok', click: () => { const n = m.n.trim().toUpperCase(); const arr = DB.lists[el.dataset.k]; const i = arr.indexOf(el.dataset.n); if (!n || i < 0) return false; arr[i] = n; (el.dataset.k === 'ptFolders' ? DB.docs : []).forEach(d => { if (d.folder === el.dataset.n) d.folder = n; }); DB.staff.forEach(s => s.docs.forEach(d => { if (el.dataset.k === 'staffFolders' && d.folder === el.dataset.n) d.folder = n; })); save(); refresh(); } }, { label: 'Cancel', cls: 'btn-del' }] }); } });
ACT.foDel = el => needApproval({ roles: ['Administrator'], what: 'Delete a record folder', rule: 'Never delete a folder that has documents in it. Never click Delete without written authorization.', who: 'Administrator, in writing', ref: 'R2', go: () => { const used = el.dataset.k === 'ptFolders' ? DB.docs.filter(d => d.folder === el.dataset.n && !d.deleted).length : DB.staff.reduce((n, s) => n + s.docs.filter(d => d.folder === el.dataset.n && !d.deleted).length, 0); if (used) { alertBox('Folder in use', `<p>${used} document(s) are filed in <b>${esc(el.dataset.n)}</b>. A folder with documents cannot be deleted.</p>`, 'warn'); return; } confirmBox('Delete folder?', '<p>Delete ' + esc(el.dataset.n) + '?</p>', () => { DB.lists[el.dataset.k] = DB.lists[el.dataset.k].filter(x => x !== el.dataset.n); save(); refresh(); }, { yes: 'Delete', no: 'Cancel' }); } });

/* ---------------------------------------------------------------- Setup lists (simplified) */
const SETUP = {
  'setup-aide': { t: 'Aide Service Titles', key: 'aideTitles', f: [['name', 'Title']] }, 'setup-evv': { t: 'EVV Change Reasons', key: 'evvReasons', f: [['name', 'Reason']] }, 'setup-refsrc': { t: 'Referral Sources', key: 'referralSources', f: [['name', 'Referral source']] },
  'setup-missed': { t: 'Missed Visit Reasons', key: 'missedReasons', f: [['name', 'Reason']] }, 'setup-phys': { t: 'Physicians', key: 'physicians', f: [['name', 'Name (LAST, FIRST MD)'], ['npi', 'NPI (10 digits)']] },
  'setup-payers': { t: 'Payers', key: 'payers', f: [['name', 'Payer name'], ['type', 'Type']] }, 'setup-bc': { t: 'Billing Codes', key: 'billingCodes', f: [['code', 'Code'], ['desc', 'Description'], ['disc', 'Discipline']] },
};
Object.keys(SETUP).forEach(r => {
  const S = SETUP[r];
  ROUTES[r] = { render(c) {
    const rows = DB.lists[S.key].map((x, i) => (typeof x === 'string' ? { i, name: x } : Object.assign({ i }, x)));
    const tbl = DT(c, 'su', () => ({ sort: S.f[0][0], cols: [{ key: 'act', label: 'Action', sortable: false, blue: true, render: r2 => rowIcons([{ ic: 'edit', t: 'Edit', act: 'suEdit', data: { r, i: r2.i } }, { ic: 'trash', t: 'Delete', act: 'suDel', data: { r, i: r2.i }, cls: 'del' }]) }].concat(S.f.map(([k, l]) => ({ key: k, label: l, text: r2 => String(r2[k] || ''), render: r2 => esc(r2[k] || '') }))), rows }));
    return pageHead(S.t, 'Summary') + `${simplified()}<div class="bar"><h2>${ic('gear')} ${esc(S.t)}</h2><button class="btn btn-add" data-act="suAdd" data-r="${r}">${ic('plus')} Add</button></div>${tbl}<p class="small">Setup lists are controlled by the Administrator. Do not add or change anything unless the Administrator told you to.</p>`;
  } };
});
function suModal(r, i) {
  const S = SETUP[r]; const arr = DB.lists[S.key]; const ex = i >= 0 ? arr[i] : null; const obj = typeof arr[0] === 'object' && arr[0] !== null;
  const m = ctxNew({ v: ex ? (obj ? Object.assign({}, ex) : { name: ex }) : {} });
  modal({ title: (ex ? 'Edit ' : 'Add ') + S.t, ctx: m, size: 'sm', body: c => S.f.map(([k, l]) => fg(l, inp(c, 'v.' + k))).join(''), buttons: [{ label: 'Save', cls: 'btn-ok', click: () => { if (!String(m.v[S.f[0][0]] || '').trim()) { toast('The first field is required.', 'err'); return false; } if (obj) { const rec = Object.assign({}, ex || { id: uid(S.key === 'physicians' ? 'PH' : S.key === 'payers' ? 'PY' : 'BC') }, m.v); if (S.key === 'physicians') rec.name = String(rec.name).toUpperCase(); if (ex) arr[i] = rec; else arr.push(rec); } else { const v = m.v.name.trim(); if (ex) arr[i] = v; else arr.push(v); } save(); track('setup:saved'); simLog('info', 'Saved a ' + S.t + ' entry'); refresh(); } }, { label: 'Cancel', cls: 'btn-del' }] });
}
ACT.suAdd = el => needApproval({ roles: ['Administrator'], what: 'Add to ' + SETUP[el.dataset.r].t, rule: 'Setup lists belong to the Administrator.', who: 'Administrator', ref: 'R2', go: () => suModal(el.dataset.r, -1) });
ACT.suEdit = el => needApproval({ roles: ['Administrator'], what: 'Change ' + SETUP[el.dataset.r].t, rule: 'Setup lists belong to the Administrator.', who: 'Administrator', ref: 'R2', go: () => suModal(el.dataset.r, +el.dataset.i) });
ACT.suDel = el => needApproval({ roles: ['Administrator'], what: 'Delete from ' + SETUP[el.dataset.r].t, rule: 'Never delete without written authorization.', who: 'Administrator, in writing', ref: 'R2', go: () => confirmBox('Delete this entry?', '<p>Delete it from the practice list?</p>', () => { DB.lists[SETUP[el.dataset.r].key].splice(+el.dataset.i, 1); save(); refresh(); }, { yes: 'Delete', no: 'Cancel' }) });

/* ---------------------------------------------------------------- Admin: User / Security Manager */
ROUTES.users = {
  render(c) {
    const tbl = DT(c, 'us', () => ({ sort: 'username', cols: [{ key: 'act', label: 'Action', sortable: false, blue: true, render: r => rowIcons([{ ic: 'edit', t: 'Edit', act: 'usEdit', data: { id: r.id } }]) }, { key: 'username', label: 'User name', blue: true, render: r => esc(r.username) }, { key: 'name', label: 'Name', render: r => esc(r.name) }, { key: 'role', label: 'Security role', text: r => ROLE_LABEL[r.role], render: r => esc(ROLE_LABEL[r.role]) }, { key: 'staff', label: 'Linked staff', text: r => stName(ST(r.staffId)), render: r => esc(stName(ST(r.staffId))) }, { key: 'active', label: 'Status', text: r => (r.active ? 'Active' : 'Disabled'), render: r => (r.active ? '<span class="tag g">Active</span>' : '<span class="tag gr">Disabled</span>') }], rows: DB.users }));
    return pageHead('User / Security Manager', 'Summary') + `${simplified()}<div class="bar"><h2>${ic('key')} Users</h2><button class="btn btn-add" data-act="usAdd">${ic('plus')} Add</button></div><p class="small">Every person gets their own login with only the access their job needs. Remove access on the last day of work. Never share or reuse a login. HR does not create or change logins. The Administrator does.</p>${tbl}`;
  },
};
function usModal(id) {
  const ex = id ? byId(DB.users, id) : null; const m = ctxNew({ u: ex ? { username: ex.username, name: ex.name, role: ex.role, staffId: ex.staffId || '', active: ex.active, pw: '' } : { username: '', name: '', role: 'Office', staffId: '', active: true, pw: '' } });
  modal({ title: ex ? 'Edit user' : 'Add user', ctx: m, size: 'lg', body: c => `<div class="row c2">${fg('User name', inp(c, 'u.username'), { req: 1 })}${fg('Full name', inp(c, 'u.name'), { req: 1 })}${fg('Security role', sel(c, 'u.role', ROLES.map(r => [r, ROLE_LABEL[r]]), { blank: false }), { req: 1 })}${fg('Linked staff member (for clinicians)', s2(c, 'u.staffId', 'staff', { ph: 'Optional', clear: 1 }))}${fg(ex ? 'New password (leave blank to keep)' : 'Password', inp(c, 'u.pw', { type: 'password' }))}</div>${chk(c, 'u.active', 'Active (uncheck to remove access)')}`, buttons: [{ label: 'Save', cls: 'btn-ok', click: () => { const u = m.u; if (!u.username.trim() || !u.name.trim()) { toast('User name and name are required.', 'err'); return false; } if (DB.users.some(x => x.username === u.username.trim().toLowerCase() && x.id !== (ex ? ex.id : ''))) { toast('That user name already exists. Never share a login.', 'err'); return false; } if (!ex && !u.pw) { toast('Enter a password.', 'err'); return false; } const rec = ex || { id: uid('U') }; rec.username = u.username.trim().toLowerCase(); rec.name = u.name.trim(); rec.role = u.role; rec.staffId = u.staffId || null; rec.active = !!u.active; if (u.pw) rec.pw = u.pw; if (!ex) DB.users.push(rec); save(); track('users:saved'); simLog('info', (ex ? 'Changed' : 'Created') + ' user ' + rec.username); refresh(); } }, { label: 'Cancel', cls: 'btn-del' }] });
}
ACT.usAdd = () => usModal(null); ACT.usEdit = el => usModal(el.dataset.id);

/* ---------------------------------------------------------------- COVID-19 screening (patients and employees, simplified) */
const COVID_Q = [['fever', 'Fever of 100.4 F or higher, or chills'], ['cough', 'New cough'], ['breath', 'Shortness of breath'], ['taste', 'New loss of taste or smell'], ['throat', 'Sore throat'], ['exposure', 'Contact with a person with COVID-19 in the last 14 days'], ['test', 'A positive COVID-19 test in the last 10 days']];
function covidRisk(a) { const n = COVID_Q.filter(([k]) => a[k]).length; return a.test || n >= 3 ? 'High' : n >= 1 ? 'Moderate' : 'Low'; }
ROUTES.covid = {
  render(c, p) {
    if (!p.pid && !p.aid) return admSearchPage(c, 'COVID-19 Patient Screening', 'covid', { sub: 'Patient Admission Search', pre: `<div class="bar"><h2>${ic('covid')} COVID-19 Patient Screening</h2></div>` });
    const pt = P(p.pid || (byId(DB.admissions, p.aid) || {}).pid); if (!pt) return notice('Not found.', 'err');
    if (!c.s) c.s = { ans: {}, who: '' };
    const hist = DB.covid.filter(x => x.pid === pt.id).sort((a, b) => (a.date < b.date ? 1 : -1));
    return pageHead('COVID-19 Patient Screening', 'Summary') + `${simplified()}<div class="bar"><h2>${ic('user')} ${esc(ptName(pt))}</h2><button class="btn btn-back" data-act="cvBack">${ic('back')} Back</button></div><p class="small">Screen the patient before each visit. Ask every question every time.</p>${covidForm(c)}<div class="flex mt"><button class="btn btn-save" data-act="cvSave" data-pid="${pt.id}">Save screening</button></div><div class="box mt"><h4>Previous screenings</h4><table class="t"><thead><tr><th>Date</th><th>Risk level</th><th>Entered by</th></tr></thead><tbody>${hist.map(h => `<tr><td>${fmtDT(h.date)}</td><td>${esc(h.risk)}</td><td>${esc((byId(DB.users, h.by) || {}).name || '')}</td></tr>`).join('') || '<tr><td colspan="3" class="none">No screenings yet</td></tr>'}</tbody></table></div>`;
  },
};
function covidForm(c) { return `<div class="box"><h4>Questions</h4>${COVID_Q.map(([k, l]) => `<div>${chk(c, 's.ans.' + k, l)}</div>`).join('')}</div>`; }
ACT.cvBack = () => go('covid');
ACT.cvSave = el => { const c = ctxOf(el); const risk = covidRisk(c.s.ans); DB.covid.push({ id: uid('CV'), pid: el.dataset.pid, date: nowIso(), answers: Object.assign({}, c.s.ans), risk, by: DB.session.userId }); save(); track('covid:saved'); simLog('info', 'COVID-19 screening saved (' + risk + ')'); c.s = { ans: {}, who: '' }; refresh(); toast('Screening saved. Risk level: ' + risk + '.' + (risk === 'High' ? ' Tell the DON before the visit.' : ''), risk === 'High' ? 'err' : 'ok'); };
ROUTES['covid-emp'] = {
  render(c) {
    if (!c.s) c.s = { ans: {}, who: '' };
    const hist = DB.covid.filter(x => x.sid).sort((a, b) => (a.date < b.date ? 1 : -1)).slice(0, 15);
    return pageHead('COVID-19 Employee Screening', 'Summary') + `${simplified()}<div style="max-width:420px">${fg('Employee', s2(c, 's.who', 'staff', { ph: 'Enter employee' }), { req: 1 })}</div>${covidForm(c)}<div class="flex mt"><button class="btn btn-save" data-act="cvEmpSave">Save screening</button></div><div class="box mt"><h4>Recent employee screenings</h4><table class="t"><thead><tr><th>Date</th><th>Employee</th><th>Risk level</th></tr></thead><tbody>${hist.map(h => `<tr><td>${fmtDT(h.date)}</td><td>${esc(stName(ST(h.sid)))}</td><td>${esc(h.risk)}</td></tr>`).join('') || '<tr><td colspan="3" class="none">None yet</td></tr>'}</tbody></table></div>`;
  },
};
ACT.cvEmpSave = el => { const c = ctxOf(el); if (!c.s.who) { toast('Choose the employee.', 'err'); return; } const risk = covidRisk(c.s.ans); DB.covid.push({ id: uid('CV'), sid: c.s.who, date: nowIso(), answers: Object.assign({}, c.s.ans), risk, by: DB.session.userId }); save(); track('covid:emp-saved'); c.s = { ans: {}, who: '' }; refresh(); toast('Employee screening saved. Risk level: ' + risk + '.', 'ok'); };
