'use strict';
/* =====================================================================================================
   Practice guide: self-checking tasks that follow the procedures in Zenith's manual, practice documents,
   the Coach log, and saving or loading practice progress.
   ===================================================================================================== */
const S = k => (DB.stats[k] || 0);
const roeP = () => DB.patients.find(p => p.last === 'ROE' && p.first === 'RICHARD');
const roeA = () => { const p = roeP(); return p ? admOf(p.id) : null; };
const roeV = () => { const p = roeP(); return p ? DB.visits.find(v => v.pid === p.id && v.billingCode === 'BC1') : null; };
const roeAs = () => { const p = roeP(); return p ? DB.assessments.find(a => a.pid === p.id && a.type === 'OASIS') : null; };
const roeN = () => { const p = roeP(); return p ? DB.snNotes.find(n => n.pid === p.id) : null; };
const TASKS = [
  { id: 'S1', role: 'All', ref: 'S1', t: 'Log in and read the Home screen', goal: 'Sign in the right way and know where Home is.', steps: ['Click your name at the top right, then Log out.', 'Sign in as <b>intake</b> with password <b>practice</b> (or tap a login name).', 'Look at Home: the help bar and Top 10 FAQ.'], check: () => S('login') >= 1 && visited('home') },
  { id: 'S2', role: 'All', ref: 'S2', t: 'Open the main menu groups', goal: 'Know the menu names in the left list.', steps: ['Click Patient, then Scheduling, then Clinical in the left menu.', 'Click Collapse to shrink the menu, then click it again.'], check: () => S('navopen:patient') && S('navopen:sched') && S('navopen:clin') },
  { id: 'S3', role: 'Office', ref: 'S3', t: 'Find a patient: search twice and click the blue filter button', goal: 'Pressing Enter alone does not filter. The blue button does.', steps: ['Patient, then Patient Demographics and Referrals.', 'Type <b>SAMPLE</b> in Search and press Enter. Notice nothing filters.', 'Click the blue filter button. Two MARIA SAMPLE records appear.', 'Match name AND date of birth. These are two different people.'], check: () => S('search:patients') >= 1 },
  { id: 'O1', role: 'Office', ref: 'O1', t: 'Review demographics and leave the record the right way', goal: 'Open a record, check it, close it without changing anything.', steps: ['Open <b>DOE, JOHN</b> with the edit icon.', 'Read the name, date of birth, address, IDs and emergency contact.', 'Click <b>Close</b> (not Delete).'], check: () => S('demo:open') && S('demo:closed-nochange') },
  { id: 'O2', role: 'Office', ref: 'O2', t: 'Log a referral', goal: 'Enter a referral on the Referrals tab.', steps: ['Open <b>SAMPLE, MARIA</b> (born 1957), Referrals tab.', 'Click Add Referral. Referral Date, Source, Physician.', 'Click OK.'], check: () => S('referral:saved') >= 1 },
  { id: 'O3', role: 'Office', ref: 'O3', t: 'Start a new patient, then cancel the right way', goal: 'Use Cancel then Yes for a record you did not mean to start.', steps: ['On Patient Demographics click + Add. A rule box appears.', 'Continue (practice), then click Cancel.', 'Read "This unsaved document will be deleted. Are you sure?" and click Yes.'], check: () => S('pt:addclick') && S('pt:newcancel') },
  { id: 'O4', role: 'Office', ref: 'O4', t: 'Check the admission, payer and cert periods', goal: 'Verify admit date, physician and insurance without changing them.', steps: ['Patient, Admission, Insurance & Prior Auth. Open <b>SAMPLE, MARIA</b>.', 'Look at the Insurance & Prior Auth table.', 'Click Show Cert Periods and read the current period.'], check: () => S('adm:open') && S('certperiods') },
  { id: 'O5', role: 'Office', ref: 'O5, O6', t: 'Upload a document with the right name and folder', goal: 'Name it LAST_FIRST_DocumentType_MMDDYYYY and pick the right folder.', steps: ['Clinical, Electronic Health Records, open <b>SAMPLE, MARIA</b> (born 1944).', 'Click + Add. Click "use a simulator practice document" and pick the signed referral (or download one from Practice documents and choose it yourself).', 'Type the Record Name (the box tells you if the pattern is right) and choose a Folder.', 'Save & Close. Check it appears in the list.'], check: () => DB.docs.some(d => !d.deleted && d.created === todayIso() && P(d.pid) && recNameCheck(d.title, P(d.pid)).ok) },
  { id: 'O7', role: 'Office', ref: 'O7', t: 'Check order status', goal: 'Find the order that is not signed or not received.', steps: ['Clinical, General Form (Orders & Docs), open <b>SAMPLE, MARIA</b>.', 'Click the eye icon on the 09/29 order. Read Received and Signed.', 'Report it. Office staff do not create clinical orders.'], check: () => S('order:view') >= 1 },
  { id: 'O8', role: 'Office', ref: 'O8, N4', t: 'Open the 485 and the Face-To-Face window safely', goal: 'Look, run the report, close. Never fax.', steps: ['Clinical, 485, open <b>SAMPLE, MARIA</b>.', 'Click F2F, choose an Encounter Type, click Run Report.', 'Close the report, then click Close on the F2F window. (Send Report as Fax is blocked.)'], check: () => S('f2f:opened') && S('f2f:report') && S('f2f:closed') },
  { id: 'O9', role: 'Office', ref: 'O9, AD2', t: 'Read All Documents', goal: 'See Visit Status and QA Status for every document.', steps: ['Open an admission, GoTo, All Documents (or the GoTo button on the right).', 'Read Visit Status and QA Status. Change the Certification Period.'], check: () => visited('alldocs') },
  { id: 'SC1', role: 'Scheduler', ref: 'SC1', t: 'Schedule a routine visit', goal: 'Right patient, right clinician, right billing code.', steps: ['Scheduling, Scheduler. Pick the patient <b>SAMPLE, MARIA</b> (born 1944).', 'Click an empty day in the calendar.', 'Choose the Caregiver, times, Billing Code. Leave Visit Status as Not Completed. Never check Do not validate for Time Conflict.', 'Save and Close and look for the new bar.'], check: () => S('visit:created') >= 1 },
  { id: 'SC2', role: 'Scheduler', ref: 'SC2', t: 'Look at a schedule and View Frequency', goal: 'Looking is always allowed. Changing needs authorization.', steps: ['In the Scheduler pick a patient, then click View Frequency.', 'Try week and day views and Cert Period View.', 'Open a visit, change the time, and write who authorized it in Comments (administrative use only).'], check: () => S('sched:freq') && S('sched:week') && S('sched:cert') },
  { id: 'SC3', role: 'Scheduler', ref: 'SC3', t: 'Use the Monitor to find a late visit', goal: 'Catch delayed visits early and tell the DON.', steps: ['CareConnect/EVV, Monitor. Today is 09/30/2026.', 'Use <b>+1 hour</b> at the top to move the practice clock. Watch the Delayed column.', 'Tick Include Cancelled, Missed... Read every Status.'], check: () => visited('monitor') && S('clock:advance') >= 1 },
  { id: 'SC4', role: 'Scheduler', ref: 'SC4', t: 'Read EVV conflicts (report only)', goal: 'Write the conflicts down for the Administrator. Do not use the buttons.', steps: ['CareConnect/EVV, Conflicts.', 'Set Date From to 09/20/2026 and read each Conflict Reason.', 'Do NOT click End Visit, Acknowledge or Remove without Action.'], check: () => visited('conflicts') && S('conflicts:setdate') >= 1 },
  { id: 'H1', role: 'HR', ref: 'H1', t: 'Find a staff member', goal: 'Never click the red trash icon.', steps: ['Setup, Staff (Caregiver). Search TESTAIDE and click the blue filter button.', 'Open the record with the green edit icon.'], check: () => S('dtfilter:staff') >= 1 && S('staff:open') >= 1 },
  { id: 'H2', role: 'HR', ref: 'H2', t: 'Start a new hire, then cancel the right way', goal: 'Practice the form and leave it safely.', steps: ['Staff, + Add (a rule box appears). Continue.', 'Type a name and then click Cancel and Yes.'], check: () => S('staff:addclick') && S('staff:newcancel') },
  { id: 'H3', role: 'HR', ref: 'H3', t: 'Update credential dates', goal: 'Enter only dates you have seen on the actual document.', steps: ['Open <b>TESTAIDE, SAM</b>, Credential Tracking. TB screening is expired.', 'Type a new Expiration Date and click Save.', 'Confirm you saw the document.'], check: () => S('staff:credsaved') >= 1 },
  { id: 'H4', role: 'HR', ref: 'H4', t: 'Upload a staff document', goal: 'Right person, right folder.', steps: ['Open a staff record, Electronic Staff Records.', 'Confirm the name and Employee ID at the top. + Add, choose a practice document and a folder.'], check: () => S('staffdoc:upload') >= 1 },
  { id: 'H5', role: 'HR', ref: 'H5', t: 'Track an absence and write a log note', goal: 'An absence that overlaps visits must be reported to the Scheduler.', steps: ['Open <b>TESTAIDE, SAM</b>. Click Track Absences.', 'Add an absence for 10/01/2026 (he has a visit that day). Read the overlap warning.', 'Then open the Staff (Caregiver) Communication Log and add a note.'], check: () => S('staff:absence-overlap') >= 1 && S('staff:comm-added') >= 1 },
  { id: 'H6', role: 'HR', ref: 'H6', t: 'Enable CareConnect', goal: 'Only after credentials are verified, with Administrator approval.', steps: ['Open <b>TESTLPN, LEE</b>. Click Enable CareConnect.', 'Read the checks. Continue only when approved.', 'Assign the login.'], check: () => S('staff:cc-enabled') >= 1 },
  { id: 'H7', role: 'Administrator', ref: 'H7', t: 'Create a user login (Administrator only)', goal: 'HR never creates logins.', steps: ['Practice as Administrator. Admin, User / Security Manager.', 'Click Add. Give a unique user name and role.'], check: () => S('users:saved') >= 1 },
  { id: 'N1', role: 'Nurse', ref: 'N1', t: 'Clock in and out on the CareConnect phone', goal: 'Clock in only inside the home. Clock out before you leave.', steps: ['Click <b>CareConnect phone</b> at the top. Rita Testnurse (RN) is already chosen. Tap Sign in.', 'Her visit with SAMPLE, MARIA is at 11:00 AM. Use <b>+1 hour</b> twice at the top so the practice time is about 10:30.', 'Tap the visit. In Practice controls set My location to the patient\'s home. Tap Clock In.', 'Tap Document the visit, finish and sign, then tap Clock Out.', 'Try a second visit while "In my car": the Conflicts screen will show the GPS conflict.'], check: () => S('phone:clockin') >= 1 && S('phone:clockout') >= 1 },
  { id: 'N2', role: 'Nurse', ref: 'N2', t: 'Start an assessment', goal: 'One SOC OASIS per admission.', steps: ['Clinical, Assessments (OASIS/NON-OASIS). Open <b>SAMPLE, MARIA</b> and + Add: you will be warned an SOC exists.', 'Practice with the SOC scenario below to create a new one.'], check: () => S('assess:created') >= 1 || S('assess:open') >= 1 },
  { id: 'N3', role: 'Nurse', ref: 'N3', t: 'Read a note in View mode, then sign your own note', goal: 'Errors block signing. Only the owner signs.', steps: ['Clinical, Skilled Nursing Visit Notes, open <b>DOE, JOHN</b>. Action menu, View, OK.', 'Click each of the ten tabs.', 'Then finish a note of your own on the phone: choose <b>Alex Testrn (RN)</b>. His 07:30 visit is already clocked in. Document the visit. On the QA/Signature tab fix every error, then sign.'], check: () => S('sn:view') >= 1 && S('sn:completed') >= 1 },
  { id: 'N5', role: 'Nurse', ref: 'N4, N5', t: 'Create a 485 and an order', goal: 'Clinical staff create them. Office staff check them.', steps: ['Clinical, 485: + Add for a patient.', 'Clinical, General Form: + Add an order.'], check: () => S('f485:created') >= 1 && S('order:saved') >= 1 },
  { id: 'AI1', role: 'Aide', ref: 'AI1', t: 'Aide: clock in, complete the aide note, clock out', goal: 'Mark every task done or say why not.', steps: ['Open the phone, choose <b>Sam Testaide (HHA)</b>.', 'Open a visit, Clock In (at the home), Document the visit.', 'Mark each task, sign, Complete. Then Clock Out.'], check: () => S('aide:note-completed') >= 1 },
  { id: 'AI2', role: 'Nurse', ref: 'AI2', t: 'Create an Aide Plan of Care (RN only)', goal: 'Aides do not create it. The RN does.', steps: ['Clinical, Aide Documents, open a patient, + Add, Plan of Care.', 'Choose the aide, dates and tasks. Save.'], check: () => S('aide:poc') >= 1 },
  { id: 'BI1', role: 'Biller', ref: 'BI1', t: 'Pull the Pre-Billing QA list', goal: 'Find what is missing before billing.', steps: ['Billing, Pre-Billing QA. Pick the period and Due but not done.', 'Click Show List and read every missing item.'], check: () => S('prebill:shown') >= 1 },
  { id: 'BI2', role: 'Biller', ref: 'BI2', t: 'Prepare a Notice of Admission (practice)', goal: 'Target: within 5 calendar days of the SOC date.', steps: ['Billing, Generate Claims PDGM. Find SAMPLE, MARIA (SOC 09/28).', 'Prepare NOA. Check the SOC date and Medicare ID. The Administrator reviews and submits (practice).'], check: () => S('noa:prepared') >= 1 },
  { id: 'BI3', role: 'Biller', ref: 'BI3', t: 'Billing screens are look only', goal: 'Prove you know the buttons you must never click.', steps: ['Billing, Generate Claims. Click Generate Claims and read why it is blocked.', 'Open Claim Summary.'], check: () => S('billing:blocked') >= 1 && visited('claimsum') },
  { id: 'AD1', role: 'DON', ref: 'AD1', t: 'QA Center: list Pending documents and approve one', goal: 'The DON approves clinical documents.', steps: ['QA Center: Document type SN Note, Status <b>Pending</b>, tick All, List Documents.', 'Select the 09/28 note, click View, then Approve (DON).'], check: () => S('qa:listed-pending') >= 1 && S('qa:approved') >= 1 },
  { id: 'AD3', role: 'Administrator', ref: 'AD3', t: 'Add a patient record folder', goal: 'Add REFERRALS and FACE-TO-FACE.', steps: ['Setup, Patient Electronic Document Folder, + Add.', 'Type REFERRALS in capital letters. Save. Check it shows in the upload window.'], check: () => S('folder:added') >= 1 },
  { id: 'AD4', role: 'Administrator', ref: 'AD4', t: 'Resolve an EVV conflict with a reason', goal: 'Only the Administrator resolves conflicts, with an EVV Change Reason.', steps: ['CareConnect/EVV, Conflicts. Choose the 09/28 conflict.', 'Click Review GPS Information first. Then Acknowledge with an EVV Change Reason.'], check: () => S('conflicts:resolved') >= 1 },
  { id: 'M1', role: 'All', ref: 'S2', t: 'Send an AloraMail and run a report', goal: 'Keep private data out of messages.', steps: ['AloraMail, New message. Try typing a fake SSN (123-45-6789) and read the warning.', 'Send a clean message. Then Reports, run Active Census.'], check: () => S('mail:sent') >= 1 && S('report:run') >= 1 },
  { id: 'C1', role: 'All', ref: 'S2', t: 'Complete a COVID-19 screening', goal: 'Screen before each visit.', steps: ['COVID-19 Screening, Patient Screening, pick a patient.', 'Answer the questions and save.'], check: () => S('covid:saved') >= 1 },
  { id: 'SOC', role: 'Scenario', ref: 'SOC Desk Checklist', t: 'SCENARIO: a full Start of Care for ROE, RICHARD', goal: 'Do every step from referral to approved note. Use ROE, RICHARD, born 03/15/1950, Medicare ID 2AA3-BB4-CC55, physician TEST PHYSICIAN, MD.',
    subs: [
      ['Create the patient ROE, RICHARD (search twice first; + Add needs Administrator approval)', () => !!roeP()],
      ['Add the referral (source Sample General Hospital)', () => !!roeP() && DB.referrals.some(r => r.pid === roeP().id)],
      ['Add the admission: admit date today, physician, status Admitted', () => !!roeA() && !!roeA().physId && roeA().status === 'Admitted'],
      ['Add insurance: MEDICARE (PRACTICE) with the member ID', () => !!roeA() && roeA().ins.some(i => i.memberId && /MEDICARE/i.test(payerName(i.payer)))],
      ['Add a diagnosis and the disciplines RN and PT, and frequency', () => !!roeA() && roeA().diag.length > 0 && roeA().disciplines.length > 0 && roeA().freq.length > 0],
      ['Upload the referral, order and Face-to-Face with correct names and folders', () => !!roeP() && DB.docs.filter(d => d.pid === roeP().id && !d.deleted && recNameCheck(d.title, roeP()).ok).length >= 3],
      ['Schedule the SOC visit with an RN and the SOC billing code (note who approved)', () => !!roeV() && !!roeV().cgId],
      ['On the phone, the RN clocks in at the home and out', () => !!roeV() && !!roeV().evv.inAt && !!roeV().evv.outAt && /patient's home/i.test((roeV().evv.inGps || {}).where || '')],
      ['Start and complete the SOC OASIS', () => !!roeAs() && (roeAs().qa === 'Pending' || roeAs().qa === 'Completed')],
      ['Write and sign the SN note with no errors', () => !!roeN() && roeN().status === 'Completed'],
      ['The DON approves the OASIS and the note in the QA Center', () => !!roeAs() && roeAs().qa === 'Completed' && !!roeN() && roeN().qa === 'Completed'],
      ['The Administrator prepares and submits the practice NOA', () => !!roeA() && ((DB.noa.find(n => n.aid === roeA().id) || {}).status === 'Submitted')],
    ] },
];
TASKS.forEach(t => { if (t.subs) t.check = () => t.subs.every(s => s[1]()); });

/* ---------------------------------------------------------------- the drawer */
const DRW = { open: false, tab: 'tasks', filter: 'mine', openTask: '', docPid: 'P2' };
let checkTimer = null;
function checkTasks() {
  if (!DB || !DB.session.userId) return;
  let n = 0; TASKS.forEach(t => { if (!DB.tasksDone[t.id]) { let ok = false; try { ok = !!t.check(); } catch (e) { ok = false; } if (ok) { DB.tasksDone[t.id] = nowIso(); n++; toast('Practice task complete: ' + t.t, 'ok'); } } });
  if (n) { try { localStorage.setItem(KEY, JSON.stringify(DB)); } catch (e) { /* ignore */ } drawerRefresh(); }
}
function checkTasksSoon() { if (checkTimer) return; checkTimer = setTimeout(() => { checkTimer = null; checkTasks(); }, 250); }
ACT.drawer = el => { DRW.open = true; DRW.tab = el.dataset.t || 'tasks'; const um = $('#usermenu .dd'); if (um) um.hidden = true; drawerRefresh(); };
ACT.drawerClose = () => { DRW.open = false; drawerRefresh(); };
ACT.drawerTab = el => { DRW.tab = el.dataset.t; drawerRefresh(); };
ACT.taskOpen = el => { DRW.openTask = DRW.openTask === el.dataset.id ? '' : el.dataset.id; drawerRefresh(); };
ACT.taskFilter = el => { DRW.filter = el.dataset.f; drawerRefresh(); };
function roleMatch(t) { if (DRW.filter === 'all') return true; const r = curRole(); return t.role === 'All' || t.role === 'Scenario' || t.role === r || (r === 'Administrator') || (r === 'DON' && t.role === 'Nurse'); }
function drawerRefresh() {
  const root = $('#drawer-root'); if (!root) return; if (!DRW.open || !DB || !DB.session.userId) { root.innerHTML = ''; return; }
  const done = TASKS.filter(t => DB.tasksDone[t.id]).length; const pct = Math.round(done / TASKS.length * 100);
  const body = DRW.tab === 'tasks' ? drwTasks(done, pct) : DRW.tab === 'docs' ? drwDocs() : DRW.tab === 'log' ? drwLog() : drwAbout();
  const sc = $('#drawer .db'); const sy = sc ? sc.scrollTop : 0;
  root.innerHTML = `<div id="drawer"><div class="dh"><div><b>Practice guide</b><div style="font-size:11px;opacity:.85">Role now: ${esc(ROLE_LABEL[curRole()] || '')}</div></div><button data-act="drawerClose" aria-label="Close">&times;</button></div><div class="dtabs">${[['tasks', 'Tasks'], ['docs', 'Practice documents'], ['log', 'Coach log'], ['about', 'About']].map(([k, l]) => `<button class="${DRW.tab === k ? 'on' : ''}" data-act="drawerTab" data-t="${k}">${l}</button>`).join('')}</div><div class="db">${body}</div></div>`;
  const sc2 = $('#drawer .db'); if (sc2) sc2.scrollTop = sy;
}
function drwTasks(done, pct) {
  const list = TASKS.filter(roleMatch);
  return `<div><b>${done} of ${TASKS.length} tasks done</b></div><div class="prog"><i style="width:${pct}%"></i></div><div class="btngrp" style="margin-bottom:8px"><button class="${DRW.filter === 'mine' ? 'on' : ''}" data-act="taskFilter" data-f="mine">For my role</button><button class="${DRW.filter === 'all' ? 'on' : ''}" data-act="taskFilter" data-f="all">All tasks</button></div><p class="small">Each task follows a procedure in Zenith's manual and checks itself when you do it. Use <b>Practice as</b> at the top to switch jobs.</p>
    ${list.map(t => { const ok = DB.tasksDone[t.id]; const open = DRW.openTask === t.id; return `<div class="task${ok ? ' done' : ''}${open ? ' open' : ''}"><div class="th" data-act="taskOpen" data-id="${t.id}"><span class="ck">${ok ? '&#10003;' : ''}</span><span><b>${esc(t.t)}</b></span><span class="rl">${esc(t.role)}</span></div><div class="tb"><div class="small">Manual: ${esc(t.ref)}</div><p><b>Goal.</b> ${esc(t.goal)}</p>${t.steps ? `<ol>${t.steps.map(s => `<li>${s}</li>`).join('')}</ol>` : `<ol>${t.subs.map(s => { let k = false; try { k = s[1](); } catch (e) { k = false; } return `<li style="list-style:none;margin-left:-16px"><span style="color:${k ? '#3c9a46' : '#999'}">${k ? '&#10003;' : '&#9675;'}</span> ${esc(s[0])}</li>`; }).join('')}</ol>`}${ok ? `<div class="small" style="color:#3c9a46">Done ${fmtDT(DB.tasksDone[t.id])}</div>` : ''}</div></div>`; }).join('') || '<p class="small">No tasks for this role. Choose All tasks.</p>'}`;
}
function drwDocs() {
  const pt = P(DRW.docPid) || DB.patients[0]; const docs = pt ? practiceDocsFor(pt) : [];
  return `<p class="small">Made-up documents for practice. Every page says SAMPLE DOCUMENT FOR TRAINING. Download one, then upload it in <b>Clinical, Electronic Health Records, + Add</b> (or use the quick menu in the upload window). A TRAP document belongs to a different patient: if you see the wrong name, STOP.</p><div class="fg"><label>Practice patient</label><select id="drwPt">${DB.patients.filter(p => !p.draft).map(p => `<option value="${p.id}"${p.id === pt.id ? ' selected' : ''}>${esc(ptName(p))} (DOB ${fmtD(p.dob)})</option>`).join('')}</select></div>
    <div class="docgrid">${docs.map((d, i) => `<div class="dc"><img src="${d.url()}" alt="${esc(d.label)}"><div style="margin:4px 0"><b>${esc(d.label)}</b></div><div class="tiny">${esc(d.file)}</div><button class="btn btn-add btn-sm" data-act="docDl" data-i="${i}">Download PNG</button> <button class="btn btn-light btn-sm" data-act="docPrev" data-i="${i}">Look</button></div>`).join('')}</div>`;
}
document.addEventListener('change', e => { if (e.target.id === 'drwPt') { DRW.docPid = e.target.value; drawerRefresh(); } });
function practiceDocList() { const pt = P(DRW.docPid) || DB.patients[0]; return practiceDocsFor(pt); }
ACT.docPrev = el => { const d = practiceDocList()[+el.dataset.i]; modal({ title: esc(d.label), size: 'lg', body: `<img class="docview img" src="${d.url()}" alt="">`, buttons: [{ label: 'Close', cls: 'btn-close' }] }); };
ACT.docDl = el => {
  const d = practiceDocList()[+el.dataset.i]; const img = new Image(); img.onload = () => { const cv = document.createElement('canvas'); cv.width = 850; cv.height = 1100; const g = cv.getContext('2d'); g.fillStyle = '#fff'; g.fillRect(0, 0, 850, 1100); g.drawImage(img, 0, 0, 850, 1100); cv.toBlob(b => { const a = document.createElement('a'); a.href = URL.createObjectURL(b); a.download = d.file.replace(/\.svg$/, '.png'); document.body.appendChild(a); a.click(); setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 800); }, 'image/png'); toast('Practice document downloaded: ' + d.file.replace(/\.svg$/, '.png'), 'sim'); track('docs:downloaded'); };
  img.onerror = () => downloadText(d.file, decodeURIComponent(d.url().split(',')[1]), 'image/svg+xml'); img.src = d.url();
};
function drwLog() {
  const c = { good: 0, override: 0, blocked: 0 }; DB.log.forEach(l => { if (c[l.kind] != null) c[l.kind]++; });
  return `<div class="flex" style="gap:8px;flex-wrap:wrap"><span class="tag g">${c.good} good choices</span><span class="tag o">${c.override} went ahead without approval</span><span class="tag r">${c.blocked} blocked</span><span class="grow"></span><button class="btn btn-light btn-sm" data-act="logClear">Clear</button></div><p class="small mt">Every coaching box and blocked action is written here with the practice time. A good habit: stop and ask.</p>${DB.log.map(l => `<div class="logrow ${l.kind}"><time>${fmtDT(l.t)} &middot; ${esc(l.role || '')} ${esc(l.user || '')}</time>${esc(l.msg)}</div>`).join('') || '<p class="small">Nothing yet.</p>'}`;
}
ACT.logClear = () => { DB.log = []; save(); drawerRefresh(); };
function drwAbout() {
  return `<p><b>AloraPlus Training Simulator.</b> A working practice copy of the screens in Zenith's Alora Operating Manual (captured 09/30/2026). It is <b>not</b> the real Alora and not affiliated with or endorsed by Alora Healthcare Systems.</p>
  <ul><li><b>Nothing leaves this browser.</b> No faxes, claims, exports, emails or uploads are ever sent.</li><li><b>Real versus simplified.</b> Screens that were photographed in the manual are copied closely. Others say <span class="chip simp">SIMPLIFIED PRACTICE VERSION</span>.</li><li><b>Not everything.</b> It covers every screen and workflow in the manual, not all of Alora. Menu items the manual does not cover say "Not built in this simulator".</li></ul>
  <div class="flex mt" style="flex-wrap:wrap"><button class="btn btn-add" data-act="progSave">Save my progress to a file</button><label class="btn btn-light">Load a progress file<input type="file" id="progLoad" accept=".json,application/json" style="display:none"></label></div><div class="mt"><button class="btn btn-del" data-act="resetAll">Reset all practice data</button></div>`;
}
ACT.progSave = () => { downloadText('alora-simulator-progress.json', JSON.stringify({ app: 'alora-sim', v: SEED_VERSION, db: DB, files: FILES }), 'application/json'); toast('Progress saved to a file on this computer.', 'sim'); };
document.addEventListener('change', e => { if (e.target.id !== 'progLoad') return; const f = e.target.files[0]; if (!f) return; const rd = new FileReader(); rd.onload = () => { try { const o = JSON.parse(String(rd.result)); if (o.app !== 'alora-sim' || o.v !== SEED_VERSION) throw new Error('This is not a progress file for this version of the simulator.'); DB = o.db; FILES = o.files || {}; saveFiles(); save(); closeAllModals(); buildShell(); render(); toast('Progress loaded.', 'ok'); drawerRefresh(); } catch (x) { alertBox('Could not load', '<p>' + esc(x.message) + '</p>', 'warn'); } }; rd.readAsText(f); });
